Add backend
Redoublet-org/Redoublet-website pull request #10
Opened 2023-03-07 09:41 UTC by MatthijsdeHeus

- Backend toegevoegd
- Docker-containers voor front- en backend icm docker-compose
- Basic interactie met backend (Play Against Robot -> Random Board -> Play Alone)

- Frontend (http://localhost:8080)
- Backend (http://localhost:5000/swagger)

2023-03-07 10:14 UTC, TheGoldenFyre requested changes
Zie comments. rest ziet er wel goed uit :)

2023-03-07 10:14 UTC, TheGoldenFyre commented on Redoublet-backend/Redoublet-backend/Models/Gamestate.cs
> +        public int Value { get; set; }
Is het niet handiger om voor card value misschien ook iets van een enum voor te maken?

2023-03-07 10:14 UTC, TheGoldenFyre commented on Redoublet-backend/Redoublet-backend/Models/Gamestate.cs
> +        public string Name4 {get; set; }
Welke name is welke? Ik ga uit van North -> East -> South -> West, maar miss handig om expliciet te maken

2023-03-07 10:14 UTC, TheGoldenFyre commented on Redoublet-backend/Redoublet-backend/Services/ConvertService.cs
> +        // Method to parse Gamestate object into json
Misschien ff comment aanpassen, want vlgm staan ze omgedraaid

2023-03-07 10:14 UTC, TheGoldenFyre commented on Redoublet-backend/Redoublet-backend/Services/ConvertService.cs
> +        // Method to parse json object into Gamestate
Zie comment hierboven

2023-03-07 10:14 UTC, TheGoldenFyre commented on Redoublet-frontend/src/views/GameView.vue
> +}
Is het misschien handig om dit in een apart bestand te zetten? Ik neem aan dat deze interfaces door wel meer components en views gebruikt gaan worden

2023-03-07 10:14 UTC, TheGoldenFyre commented on Redoublet-frontend/src/views/GameView.vue
> +            Name4: 'speler 4',
Again miss handig om richtingen expliciet te maken

2023-03-07 10:21 UTC, MatthijsdeHeus commented on Redoublet-backend/Redoublet-backend/Models/Gamestate.cs
> +        public int Value { get; set; }
Bedoel je dan iets van de getallen 1 tm 10 en dan bijv B, V, K en A voor de plaatjes?

Dat kunnen we hier doen, maar maakt in principe geen verschil toch met renderen?

2023-03-07 10:21 UTC, MatthijsdeHeus commented on Redoublet-backend/Redoublet-backend/Models/Gamestate.cs
> +        public int Value { get; set; }
Als we getallen doen kunnen we ook makkelijk kijken wat hoger is.

2023-03-07 10:32 UTC, MatthijsdeHeus commented on Redoublet-backend/Redoublet-backend/Services/ConvertService.cs
> +        // Method to parse Gamestate object into json
Done!

2023-03-07 10:34 UTC, MatthijsdeHeus commented on Redoublet-frontend/src/views/GameView.vue
> +            Name4: 'speler 4',
Done

2023-03-07 10:58 UTC, TheGoldenFyre commented on Redoublet-backend/Redoublet-backend/Models/Gamestate.cs
> +        public int Value { get; set; }
Zou in principe geen verschil maken met renderen, maar kan wel wat problemen voorkomen met out of range values. Je zou ook eventueel nog de waarden A = 13, K = 12, etc toe kunnen voegen aan de enum zodat vergelijkingen nog goed gaan

2023-03-07 11:01 UTC, TheGoldenFyre commented on Redoublet-frontend/src/views/GameView.vue
> +}
We zouden evt een apart mapje met Datastructuren kunnen aanmaken ofzo, en hierin alleen .ts files plaatsen die geimporteerd kunnen worden?

2023-03-07 11:10 UTC, MatthijsdeHeus commented on Redoublet-backend/Redoublet-backend/Models/Gamestate.cs
> +        public int Value { get; set; }
Wat vind je van deze implementatie?

2023-03-07 11:11 UTC, MatthijsdeHeus commented on Redoublet-frontend/src/views/GameView.vue
> +}
Kunnen we zeker doen, hebben andere mensen hier nog een mening over?

2023-03-07 11:14 UTC, Nightshades24 requested changes

2023-03-07 11:14 UTC, Nightshades24 commented on Redoublet-frontend/package.json
> -    "build": "run-p type-check build-only",
Waarom heb je dit eruit gehaald?

2023-03-07 11:14 UTC, Nightshades24 commented on Redoublet-frontend/src/components/DefaultGrid.vue
> +interface Row {
Een row? Van wat voor grid? Ik zou hier graag een comment met informatie zien.

2023-03-07 11:14 UTC, Nightshades24 commented on Redoublet-frontend/src/views/GameView.vue
> +  cards: Card[];
Staat hier de beginhand in opgeslagen?

2023-03-07 11:14 UTC, Nightshades24 commented on Redoublet-frontend/src/views/GameView.vue
> +  value: number;
Welke value heeft de aas?

2023-03-07 11:14 UTC, Nightshades24 commented on Redoublet-frontend/src/views/GameView.vue
> +
Hier moet een enter weg

2023-03-07 11:14 UTC, Nightshades24 commented on Redoublet-frontend/src/views/GameView.vue
> +            Name1: 'Speler 1',
Moeten de spelernamen geen variabelen zijn?

2023-03-07 11:14 UTC, Nightshades24 commented on Redoublet-frontend/src/views/GameView.vue
> +
Hier moet een enter weg

2023-03-07 11:14 UTC, Nightshades24 commented on Redoublet-frontend/src/views/GameView.vue
> +
Verwijder hier overbodige enters

2023-03-07 11:14 UTC, Nightshades24 commented on Redoublet-frontend/src/views/GameView.vue
> +
Overbodige enter weghalen

2023-03-07 11:14 UTC, Nightshades24 commented on Redoublet-frontend/src/views/GameView.vue
> +
Overbodige enter weghalen

2023-03-07 11:14 UTC, Nightshades24 commented on Redoublet-frontend/src/views/PlayerHomeView.vue
> +import TestBoardBox from "../components/TestBoardBox.vue";
Moet deze import niet weg gezien testboard is verwijderd?

2023-03-07 11:14 UTC, Nightshades24 commented on Redoublet-frontend/src/views/MultiplayerCompetitionJoinView.vue
> +  { Table: '#1', Players: '2 / 4 ', 'PartnerSystem': 'ACOL', 'AvgRating': '7.5', Countdown: '01:50m' },
Moeten deze placeholders in de pull request staan?

2023-03-07 11:24 UTC, TheGoldenFyre commented on Redoublet-backend/Redoublet-backend/Models/Gamestate.cs
> +        public int Value { get; set; }
Ziet er goed uit!

2023-03-07 11:26 UTC, MatthijsdeHeus commented on Redoublet-backend/Redoublet-backend/Controllers/BridgeGameLogic.cs
> +        private readonly ILogger<BridgeGameLogic> _logger;
Sure

2023-03-07 11:29 UTC, MatthijsdeHeus commented on Redoublet-backend/Redoublet-backend/Program.cs
> +                          .AllowAnyHeader()
Done

2023-03-07 11:30 UTC, MatthijsdeHeus commented on Redoublet-frontend/Dockerfile
> +RUN npm install && npm run build
Zeker

2023-03-07 11:32 UTC, MatthijsdeHeus commented on Redoublet-frontend/package.json
> -    "build": "run-p type-check build-only",
Dit geeft een error bij het builden omdat we nog niet alle types klaar hebben liggen. 

Als het goed is wordt er in de code cleanup naar gekeken toch? @sebas42069

2023-03-07 11:39 UTC, MatthijsdeHeus commented on Redoublet-frontend/src/components/DefaultGrid.vue
> +interface Row {
Dus ook geen comment nodig haha

2023-03-07 11:41 UTC, MatthijsdeHeus commented on Redoublet-frontend/src/views/GameView.vue
> +
Done

2023-03-07 11:43 UTC, Nightshades24 commented on Redoublet-frontend/package.json
> -    "build": "run-p type-check build-only",
Oke top!

2023-03-07 11:43 UTC, MatthijsdeHeus commented on Redoublet-frontend/src/views/PlayerHomeView.vue
> +import TestBoardBox from "../components/TestBoardBox.vue";
Zeker

2023-03-07 11:46 UTC, MatthijsdeHeus commented on Redoublet-frontend/src/views/MultiplayerCompetitionJoinView.vue
> +  { Table: '#1', Players: '2 / 4 ', 'PartnerSystem': 'ACOL', 'AvgRating': '7.5', Countdown: '01:50m' },
Komt nog uit de demo, lijkt mij dat het voor nu kan blijven staan.

2023-03-07 11:48 UTC, MatthijsdeHeus commented on Redoublet-frontend/src/views/GameView.vue
> +  cards: Card[];
Nog niet, komt in latere PR's.

2023-03-07 11:48 UTC, MatthijsdeHeus commented on Redoublet-frontend/src/views/GameView.vue
> +
Done

2023-03-07 11:49 UTC, Nightshades24 commented on Redoublet-frontend/src/views/MultiplayerCompetitionJoinView.vue
> +  { Table: '#1', Players: '2 / 4 ', 'PartnerSystem': 'ACOL', 'AvgRating': '7.5', Countdown: '01:50m' },
Prima

2023-03-07 11:50 UTC, MatthijsdeHeus commented on Redoublet-frontend/src/views/GameView.vue
> +            Name1: 'Speler 1',
Zodra gebruikers ergens via formulieren hun naam in kunnen vullen moet dat wel, voor nu lijkt mij dit voldoende als voorbeeld.

2023-03-07 11:51 UTC, MatthijsdeHeus commented on Redoublet-frontend/src/views/GameView.vue
> +
Gedaan

2023-03-09 08:11 UTC, Nightshades24 commented on Redoublet-frontend/src/views/GameView.vue
> +}
Klinkt goed

2023-03-09 08:49 UTC, Nightshades24 requested changes

2023-03-09 08:49 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Program.cs
> +// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
Moet deze comment niet 1 regel naar boven? Of anders een witregel ertussen voor meer overzicht

2023-03-09 08:49 UTC, Nightshades24 commented on Redoublet-frontend/src/views/GameView.vue
> +}
Moet wel elke interface in een aparte file komen, en laat de namen met een hoofdletter i beginnen zodat het duidelijk is dat het een interface is

2023-03-09 08:49 UTC, Nightshades24 commented on Redoublet-frontend/src/views/GameView.vue
> +            NameSouth: 'speler 3',
"Speler" en  "speler", dit kan mn autisme echt niet hebben

2023-03-09 08:49 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Models/Gamestate.cs
> +{
Alle models hierin moeten in een eigen klasse, in een eigen .cs bestand. Eventuele bijbehorende enums mogen wel in het .cs bestand erbij staan

2023-03-09 12:06 UTC, Nightshades24 commented
Changes zijn verplaatst naar een andere branch, daarvoor wordt nu een pullrequest gemaakt

2023-03-09 12:38 UTC, rubenfranquinet approved these changes

2023-03-09 12:39 UTC, Nightshades24 approved these changes

2023-03-09 12:39 UTC, merged