Feature 318 speelveld assets
Redoublet-org/Redoublet-website pull request #102
Opened 2023-06-27 17:07 UTC by sebas42069

Assets verwerkt. Voor nu alleen in singleplayer

2023-06-27 17:20 UTC, rubenfranquinet requested changes
Achteraf kan ik niet meer zien wat het contract was en is de map oplevering-202306..... nodig? Lijkt alsof deze assets ook in de andere mappen staan

2023-06-27 17:20 UTC, rubenfranquinet commented on Redoublet-frontend/public/assets/oplevering-20230627T135121Z-001.zip
Wat is deze zip file? Mag die weg?

2023-06-27 17:23 UTC, rubenfranquinet commented
oh en dit
![image](https://github.com/Redoublet-org/Redoublet-website/assets/64008619/0436fc6f-742b-48f7-a842-028e9136c22d)

2023-06-27 17:27 UTC, tvdplas commented
![image](https://github.com/Redoublet-org/Redoublet-website/assets/20602812/7a2f301f-4f0b-49cd-8674-5cbcec35833f)
Randjes rondom de actieve speler zijn een klein beetje raar

2023-06-27 17:29 UTC, tvdplas requested changes
Qua code ziet het er prima uit, zie wel comment.

Misschien een beetje out of scope maar let ook op dat de optimale contracten nog (deels) in het engels staan
![image](https://github.com/Redoublet-org/Redoublet-website/assets/20602812/5c8a14d8-4cb1-4d6e-bb2e-4e6175cbb2f6)

2023-06-27 17:42 UTC, rubenfranquinet commented
nog een kleine comment:
![image](https://github.com/Redoublet-org/Redoublet-website/assets/64008619/0eb403e8-0689-4794-ba9b-6e675e99de04)

2023-06-27 19:08 UTC, sebas42069 commented on Redoublet-frontend/public/assets/oplevering-20230627T135121Z-001.zip
yep kan weg

2023-06-27 19:58 UTC, sebas42069 commented
> Qua code ziet het er prima uit, zie wel comment.
> 
> Misschien een beetje out of scope maar let ook op dat de optimale contracten nog (deels) in het engels staan ![image](https://user-images.githubusercontent.com/20602812/249234750-5c8a14d8-4cb1-4d6e-bb2e-4e6175cbb2f6.png)

ja idd out of scope, daar is al wel een taakje voor in jira

2023-06-27 21:02 UTC, rubenfranquinet reviewed
alleen dit streepje mag nog weg, verder helemaal top
<img width="128" alt="image" src="https://github.com/Redoublet-org/Redoublet-website/assets/64008619/b47f5300-07d7-4508-acd6-e0fb958c9263">

2023-06-27 21:06 UTC, rubenfranquinet approved these changes

2023-06-27 21:30 UTC, tvdplas submitted a review, later dismissed
Dat noem ik pas echt bridge

2023-06-28 08:40 UTC, rubenfranquinet approved these changes
Alles ziet er goed uit, werkt super!

Alleen fix de linter nog eventjes

2023-06-28 09:33 UTC, merged