Code cleanup and merge with 'add backend'
Redoublet-org/Redoublet-website pull request #11
Opened 2023-03-09 12:07 UTC by sebas42069

2023-03-11 15:48 UTC, Nightshades24 requested changes

2023-03-11 15:48 UTC, Nightshades24 commented on Redoublet-website/src/components/Home/SingupBox.vue
> +</style>
Deze file moet eindigen met een witregel. Zie: https://rules.sonarsource.com/typescript/RSPEC-113

2023-03-11 15:48 UTC, Nightshades24 commented on Redoublet-website/src/components/Home/SingupBox.vue
> +<script setup lang="ts">
Kan dit script niet weg?

2023-03-11 15:48 UTC, Nightshades24 commented on Redoublet-website/src/components/Multiplayer/MultiplayerCompetitionOptions.vue
> +<script setup lang="ts">
Kan dit script niet weg?

2023-03-11 15:48 UTC, Nightshades24 commented on Redoublet-website/src/components/Multiplayer/MultiplayerCompetitionOptions.vue
> +</style>
Deze file moet eindigen met een witregel. Zie: https://rules.sonarsource.com/typescript/RSPEC-113

2023-03-11 15:48 UTC, Nightshades24 commented on Redoublet-website/src/components/Multiplayer/MultiplayerTableOptions.vue
> +<script setup lang="ts">
Kan dit script niet weg?

2023-03-11 15:48 UTC, Nightshades24 commented on Redoublet-website/src/components/Multiplayer/MultiplayerTableOptions.vue
> +</style>
Deze file moet eindigen met een witregel. Zie: https://rules.sonarsource.com/typescript/RSPEC-113

2023-03-11 15:48 UTC, Nightshades24 commented on Redoublet-website/src/components/Multiplayer/MultiplayerTournamentOptions.vue
> +<script setup lang="ts">
Kan dit script niet weg?

2023-03-11 15:48 UTC, Nightshades24 commented on Redoublet-website/src/components/Robot/RobotCompetitionOption.vue
> +</style>
Deze file moet eindigen met een witregel. Zie: https://rules.sonarsource.com/typescript/RSPEC-113

2023-03-11 15:48 UTC, Nightshades24 commented on Redoublet-website/src/components/Robot/RobotGameOption.vue
> +</style>
Deze file moet eindigen met een witregel. Zie: https://rules.sonarsource.com/typescript/RSPEC-113

2023-03-11 15:48 UTC, Nightshades24 commented on Redoublet-website/src/views/Home/CreateAccountView.vue
> +</style>
Deze file moet eindigen met een witregel. Zie: https://rules.sonarsource.com/typescript/RSPEC-113

2023-03-11 15:48 UTC, Nightshades24 commented on Redoublet-website/src/views/Home/LoginView.vue
> +</style>
Deze file moet eindigen met een witregel. Zie: https://rules.sonarsource.com/typescript/RSPEC-113

2023-03-11 15:48 UTC, Nightshades24 commented on Redoublet-website/src/views/Home/PlayerHomeView.vue
>  import MultiplayerBox from "../components/MultiplayerBox.vue";
Oude imports kunnen weg

2023-03-11 15:48 UTC, Nightshades24 commented on Redoublet-website/src/views/Multiplayer/MultiplayerCompetitionJoinView.vue
> +</style>
Deze file moet eindigen met een witregel. Zie: https://rules.sonarsource.com/typescript/RSPEC-113

2023-03-11 15:48 UTC, Nightshades24 commented on Redoublet-website/src/views/Multiplayer/MultiplayerCompetitionSetupView.vue
> +</style>
Deze file moet eindigen met een witregel. Zie: https://rules.sonarsource.com/typescript/RSPEC-113

2023-03-11 15:48 UTC, Nightshades24 commented on Redoublet-website/src/views/Multiplayer/MultiplayerTableSetupView.vue
>  </style>
Deze file moet eindigen met een witregel. Zie: https://rules.sonarsource.com/typescript/RSPEC-113

2023-03-11 15:48 UTC, Nightshades24 commented on Redoublet-website/src/views/Multiplayer/MultiplayerTableView.vue
>  </style>
Deze file moet eindigen met een witregel. Zie: https://rules.sonarsource.com/typescript/RSPEC-113

2023-03-11 15:48 UTC, Nightshades24 commented on Redoublet-website/src/views/Multiplayer/MultiplayerTournamentJoinView.vue
> +</style>
Deze file moet eindigen met een witregel. Zie: https://rules.sonarsource.com/typescript/RSPEC-113

2023-03-11 15:48 UTC, Nightshades24 commented on Redoublet-website/src/views/Multiplayer/MultiplayerTournamentSetupLiveView.vue
> +</style>
Deze file moet eindigen met een witregel. Zie: https://rules.sonarsource.com/typescript/RSPEC-113

2023-03-11 15:48 UTC, Nightshades24 commented on Redoublet-website/src/views/Multiplayer/MultiplayerTournamentSetupView.vue
> +</style>
Deze file moet eindigen met een witregel. Zie: https://rules.sonarsource.com/typescript/RSPEC-113

2023-03-11 15:48 UTC, Nightshades24 commented on Redoublet-website/src/views/Multiplayer/MultiplayerTournamentView.vue
> +</style>
Deze file moet eindigen met een witregel. Zie: https://rules.sonarsource.com/typescript/RSPEC-113

2023-03-11 15:48 UTC, Nightshades24 commented on Redoublet-website/src/views/PlayedGames/PlayedGamesView.vue
> +</style>
Deze file moet eindigen met een witregel. Zie: https://rules.sonarsource.com/typescript/RSPEC-113

2023-03-11 15:48 UTC, Nightshades24 commented on Redoublet-website/src/views/Robot/PickCompetitionView.vue
> +</style>
Deze file moet eindigen met een witregel. Zie: https://rules.sonarsource.com/typescript/RSPEC-113

2023-03-11 15:48 UTC, Nightshades24 commented on Redoublet-website/src/views/Robot/RobotCompetition.vue
> +</style>
Deze file moet eindigen met een witregel. Zie: https://rules.sonarsource.com/typescript/RSPEC-113

2023-03-11 15:48 UTC, Nightshades24 commented on Redoublet-website/src/views/Robot/RobotRandomBoard.vue
> +</style>
Deze file moet eindigen met een witregel. Zie: https://rules.sonarsource.com/typescript/RSPEC-113

2023-03-11 15:48 UTC, Nightshades24 commented on Redoublet-website/src/views/Robot/RobotRandomBoard.vue
> +
Overbodige witregel mag weg

2023-03-11 15:49 UTC, Nightshades24 commented
En voortaan graag niet meer een branch naar een andere branch mergen :)

2023-03-14 14:22 UTC, Nightshades24 requested changes

2023-03-14 14:22 UTC, Nightshades24 commented on Redoublet-frontend/src/views/Multiplayer/MultiplayerCompetitionView.vue
> +    <MultiplayerCompetitionOptions />
Die spatie moet weg

2023-03-15 10:13 UTC, sebas42069 commented on Redoublet-frontend/src/components/CreateGameGrid.vue
> -</script>
de import werd niet gebruikt

2023-03-15 10:15 UTC, sebas42069 commented on Redoublet-frontend/src/views/Multiplayer/MultiplayerCompetitionView.vue
> +    <MultiplayerCompetitionOptions />
Nee dit is een van de vue conventies voor components. zo staat het als het goed is ook bij elke andere component

2023-03-17 09:08 UTC, Nightshades24 commented
Ik had bij 2 comments waarbij jij op resolved had gedrukt weer unresolved, omdat je die niet had gefixt. Dit ging erover dat er ergens nog een newline miste aan het einde van een file en nog iets. Had je deze dit keer wel resolved? Ik zie ze namelijk niet bij je nieuwe gecommitte veranderingen staan

2023-03-19 20:42 UTC, rubenfranquinet requested changes
In github staan bij changed files de mappen Redoublet-frontend en Redoublet-website. Wat is het verschil? Lijkt me dat we alleen de map Redoublet-frontend willen en daar alle vue dingen in hebben.

2023-03-19 20:42 UTC, rubenfranquinet commented on Redoublet-frontend/src/components/Home/Competitions.vue
> +var v = time + conversion;
Zou een iets duidelijkere variabele naam gebruiken.

2023-03-19 20:42 UTC, rubenfranquinet commented on Redoublet-frontend/src/components/Multiplayer/MultiplayerCompetitionOptions.vue
> +</style>
Zet hier nog even een enter onder

2023-03-19 20:42 UTC, rubenfranquinet commented on Redoublet-frontend/src/components/Multiplayer/MultiplayerTableOptions.vue
> +</style>
zet hier ook nog even een enter onder

2023-03-19 20:42 UTC, rubenfranquinet commented on Redoublet-frontend/src/components/Robot/RobotCompetitionOption.vue
> +</style>
let hier ook nog even op de enter

2023-03-19 20:42 UTC, rubenfranquinet commented on Redoublet-frontend/src/components/Robot/RobotGameOption.vue
> +</style>
hier ook een enter

2023-03-19 20:42 UTC, rubenfranquinet commented on Redoublet-frontend/src/components/DefaultGrid.vue
> +import { onMounted } from 'vue';
Deze import wordt niet gebruikt dus zou hem weghalen

2023-03-19 20:42 UTC, rubenfranquinet commented on Redoublet-frontend/src/components/DefaultGrid.vue
> +});
Dit is options toch? Verander even naar composition.

2023-03-19 20:42 UTC, rubenfranquinet commented on Redoublet-frontend/src/components/GridButtons.vue
> +});
Deze code is ook geschreven als options

2023-03-20 10:19 UTC, sebas42069 commented on Redoublet-frontend/src/components/DefaultGrid.vue
> +});
Als het goed is is dit wel gewoon composition: https://vuejs.org/guide/typescript/composition-api.html#typing-component-props

2023-03-20 10:19 UTC, sebas42069 commented on Redoublet-frontend/src/components/GridButtons.vue
> +});
Als het goed is is dit wel gewoon composition: https://vuejs.org/guide/typescript/composition-api.html#typing-component-props

2023-03-20 12:40 UTC, rubenfranquinet approved these changes

2023-03-20 12:44 UTC, Nightshades24 approved these changes

2023-03-20 12:45 UTC, merged