Add pixi.js
Redoublet-org/Redoublet-website pull request #12
Opened 2023-03-13 13:29 UTC by rubenfranquinet

Pixi.js toegevoegd en in de component "PixiComponent.vue" toegevoegd.

2023-03-13 14:45 UTC, Toine1404 requested changes

2023-03-13 14:45 UTC, Toine1404 commented on Redoublet-frontend/package-lock.json
> +    },
hebben wij al deze modules nodig? misschien kan er gecherrypicked worden op degene die we wel nodig hebben/gaan hebben.

2023-03-13 14:45 UTC, Toine1404 commented on Redoublet-frontend/src/components/PixiComponent.vue
> +    <div id="container"></div>
id="container" is onnodig omdat deze nergens staat gedefinieerd. deze id doet niks dus kan worden weggehaald

2023-03-13 14:47 UTC, Toine1404 requested changes
de afbeelding laadt niet wanneer de front-end via docker commands wordt gerund.

2023-03-13 15:24 UTC, rubenfranquinet commented on Redoublet-frontend/package-lock.json
> +    },
Hoe bedoel je?

2023-03-13 15:29 UTC, rubenfranquinet commented on Redoublet-frontend/src/components/PixiComponent.vue
> +    <div id="container"></div>
Zie de regel `const container = document.getElementById("container");`.
Om de div in de typescript code te hebben moeten we deze eerst pakken dmv getElementById.

2023-03-14 13:25 UTC, sebas42069 commented on Redoublet-frontend/src/components/PixiComponent.vue
> +    renderer: "auto"
renderer is toch geen deel van deze options object? https://pixijs.download/v5.3.10/docs/PIXI.Application.html

2023-03-20 09:54 UTC, TheGoldenFyre approved these changes

2023-03-20 19:15 UTC, Toine1404 approved these changes

2023-03-20 19:15 UTC, merged