adding SVG files for all the card placeholders
Redoublet-org/Redoublet-website pull request #13
Opened 2023-03-13 13:31 UTC by Toine1404

added all the placeholders for the cards (front and back) via SVG files. I can also add the png files but these will unnecessarily add a lot of files to the project if they are not needed

2023-03-13 13:35 UTC, rubenfranquinet commented
Denk dat .png beter is om te gebruiken dan .svg

2023-03-14 12:53 UTC, sebas42069 commented
prima plaatjes, waarom in png formaat in plaats van svg?

2023-03-16 10:04 UTC, sebas42069 approved these changes

2023-03-19 10:41 UTC, rubenfranquinet requested changes
Waarom hebben we van sommige kaarten 2 verschillende kaarten? Zeker aangezien het placeholders zijn lijkt dit me overbodig. Volgensmij zijn jokers ook niet nodig.

2023-03-19 13:54 UTC, rubenfranquinet approved these changes

2023-03-19 14:00 UTC, merged