Tricks toegevoegd
Redoublet-org/Redoublet-website pull request #15
Opened 2023-03-15 13:32 UTC by MatthijsdeHeus

- Hele basis functionaliteit voor tricks toegevoegd.
- Eerst moet je bieden om tricks te kunnen doen.
- Beter overzicht met bieden.

(Een hoop regels zitten er nog niet in, maar dit is wel de basis)

2023-03-15 14:05 UTC, Nightshades24 commented
Wat zit er allemaal precies in qua logica? Ik kan namelijk gewoon kaarten spelen die niet de troef zijn of de soort van die trick volgen.

2023-03-15 14:46 UTC, MatthijsdeHeus commented
Qua logica zit er in:
- Niet kunnen bieden in de tricks fase
- Nu kunnen we bieden via knoppen (iets minder cursed)
- Niet kunnen spelen in de bied fase
- Werkende PlayCard endpoint in de API, d.m.v een nieuw PlayCardRequest model
- PlayCard js functie die de endpoint aanroept
- De kaarten per speler zijn nu buttons die de PlayCard methode aanroepen met de juiste parameters
- Gespeelde kaarten verwijderen uit de hand van de speler
- Gespeelde kaarten toevoegen aan de nieuwste trick
- Als de trick 4 kaarten bevat wordt de winnaar berekend
- De winnaar wordt berekend door te kijken wie de hoogste waarde kaart heeft ingezet in de suit van de kaart gespeeld door de speler die als eerste aan de beurt was
- Als een trick klaar is wordt een nieuwe trick gemaakt tenzij er geen kaarten meer zijn.

Dit leek mij een goed punt om de PR aan te maken, zodat het niet een nog grotere PR zou worden en nu de basis erin zit, kunnen we de implementatie van de regels beter verdelen qua stories en parallel eraan werken.

2023-03-15 22:56 UTC, Nightshades24 requested changes

2023-03-15 22:56 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Services/TrickService.cs
> +            if (gamestate.Tricks[gamestate.Tricks.Count - 1].PlayedCards.Count == 4 && gamestate.Tricks.Count < 13)
Bij de laatste trick wordt nu de winner niet berekend.

2023-03-15 22:56 UTC, Nightshades24 commented on Redoublet-frontend/src/views/GameView.vue
> +                        <div class="col-1"><p>No Trump</p></div>
Kan je hier iets meer ruimte in de breedte tussen zetten zodat het er wat minder cursed uit ziet?
![image](https://user-images.githubusercontent.com/71764800/225459315-2f11b900-6335-4d64-b724-ef8114ac0393.png)

2023-03-15 22:56 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Services/TrickService.cs
> +                if(card.Card.Suit == startingSuit && card.Card.Value > HighestCard.Card.Value)
Lijkt me goed om hier nu al aan toe te voegen dat hij ook rekening houdt met wat de troef is, gezien je het nu half hebt geimplementeerd.

2023-03-15 22:56 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Models/Trick.cs
> +        // Side that played the card
"The card" is niet heel duidelijk, vgm bedoel je de eerste kaart waarmee de "troef" van die slag wordt bepaald. Dat is in elk geval hoe ik het interpreteer. Zou je dit iets duidelijker kunnen verwoorden?

2023-03-15 22:56 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Services/BiddingService.cs
> +            if (bid.Amount <= 0 || bid.Amount > 7 ||
Deze verification is nu je knoppen gebruikt niet meer nodig lijkt me

2023-03-15 22:56 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Services/TrickService.cs
> +            int indexOfCard = gamestate.Players[(int)gamestate.CurrentPlayer].Cards.FindIndex(0, gamestate.Players[(int)gamestate.CurrentPlayer].Cards.Count, playerCard => playerCard.Suit == card.Sui
Dit kan echt niet korter/cleaner?

2023-03-16 09:37 UTC, sebas42069 commented on Redoublet-frontend/src/views/GameView.vue
> +interface PlayedCard {
interfaces in een externe folder

2023-03-20 10:36 UTC, MatthijsdeHeus commented on Redoublet-backend/Redoublet-backend/Services/BiddingService.cs
> +            if (bid.Amount <= 0 || bid.Amount > 7 ||
Om te voorkomen dat mensen handmatig met de URL aan de gang gaan lijkt het me veiliger om deze check erin te houden.

2023-03-20 12:49 UTC, MatthijsdeHeus commented on Redoublet-backend/Redoublet-backend/Services/TrickService.cs
> +            int indexOfCard = gamestate.Players[(int)gamestate.CurrentPlayer].Cards.FindIndex(0, gamestate.Players[(int)gamestate.CurrentPlayer].Cards.Count, playerCard => playerCard.Suit == card.Sui
Korter niet, heb het cleaner gemaakt

2023-03-20 18:57 UTC, merged