Pbn inlezen
Redoublet-org/Redoublet-website pull request #16
Opened 2023-03-16 13:24 UTC by Stayutazen

PBN kan worden ingelezen en wordt omgezet naar de GameState.
Kan ook weer naar PBN formaat worden geëxporteerd.

2023-03-18 15:19 UTC, TheGoldenFyre requested changes

2023-03-18 15:19 UTC, TheGoldenFyre commented on Redoublet-backend/Redoublet-backend/Models/PBNParser.cs
> +            select (id, val);
Miss ff wat uitleg toevoegen over hoe die parsers werken en wat ze precies doen?

2023-03-18 15:19 UTC, TheGoldenFyre commented on Redoublet-backend/Redoublet-backend/Models/PBNParser.cs
> +                    {
Is een val != currboard (of iets van de identifier van het huidige bord) hier miss niet handiger in plaats van uitgaan dat de cijfers oplopen? Want ik weet niet zeker of het verplicht is om een bord oplopend te nummeren of dat een random string gewoon als naam kan worden gebruikt

2023-03-18 15:19 UTC, TheGoldenFyre commented on Redoublet-backend/Redoublet-backend/Models/PBNParser.cs
> +                ps.Vulnerable = ((new[] { "NS", "Both", "All" }).Contains(data["Vulnerable"], StringComparer.OrdinalIgnoreCase)) ? true : false;
turnary is hier niet nodig, je zou direct `new[] { ... }).Contains(...)` kunnen gebruiken als waarde

2023-03-18 15:19 UTC, TheGoldenFyre commented on Redoublet-backend/Redoublet-backend/Models/ExportPBN.cs
> +                lines.AddRange(temp);
Misschien `temp` een iets duidelijkere naam geven

2023-03-18 15:19 UTC, TheGoldenFyre commented on Redoublet-backend/Redoublet-backend/Models/GameState.cs
Ik neem aan dat dit nog wel gaat veranderen ivm met o.a. de merge conflicts, maar misschien is het handig om wel bepaalde delen van de gamestate op te splitsen in meerdere bestanden (denk player, contract, etc) om iets meer overzicht te houden

2023-03-20 19:12 UTC, rubenfranquinet requested changes
Goeie code, probeer alleen te letten op duidelijke variabele namen.

2023-03-20 19:12 UTC, rubenfranquinet commented on Redoublet-backend/Redoublet-backend/Models/GameState.cs
> +        public void BidContract(int tricks, Face d, string side)
Misschien de variabele d een andere naam geven

2023-03-20 19:12 UTC, rubenfranquinet commented on Redoublet-backend/Redoublet-backend/Models/GameState.cs
> +        public void Double(string side, Risk d)
ook hier een andere variabele naam ipv d

2023-03-20 19:12 UTC, rubenfranquinet commented on Redoublet-backend/Redoublet-backend/Models/PBNParser.cs
> +        public void ReadMultipleGames(int i, string[] pbn)
int i, is dat het aantal games dat die moet readen? Miss ff een iets duidelijkere naam geven zoals numberOfGames.

2023-03-20 19:12 UTC, rubenfranquinet commented on Redoublet-backend/Redoublet-backend/Models/PBNParser.cs
> +                        foreach (string v in val.Split(new string[] { " " }, StringSplitOptions.RemoveEmptyEntries))
ook hier zou ik v iets duidelijkere naam geven

2023-03-20 19:12 UTC, rubenfranquinet commented on Redoublet-backend/Redoublet-backend/Models/PBNParser.cs
> +                        foreach (string v in val.Split(new string[] { " " }, StringSplitOptions.RemoveEmptyEntries))
v misschien duidelijkere naam geven

2023-03-20 19:12 UTC, rubenfranquinet commented on Redoublet-backend/Redoublet-backend/Models/PBNParser.cs
> +}
newline aan einde van de file

2023-03-21 11:00 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Models/GameState.cs
> +    }
Matthijs heeft hiervoor al een model naar main gepusht, waar deze 2 inzitten.
![image](https://user-images.githubusercontent.com/71764800/226586935-23cb0ba2-cb46-4097-a1d1-2ab6288586af.png)
![image](https://user-images.githubusercontent.com/71764800/226587012-44ea0478-7a7f-4fe0-a5ac-37eaba31bbae.png)
Als je deze ook wil moet je main even naar jouw branch mergen.

2023-03-31 09:17 UTC, rubenfranquinet approved these changes

2023-03-31 09:19 UTC, rubenfranquinet commented
Ziet er goed uit, lekker bezig! 💯

2023-03-31 09:45 UTC, TheGoldenFyre approved these changes
Ziet er wat mij betreft goed uit! Mergen die handel

2023-03-31 09:47 UTC, merged