Add remaining rules
Redoublet-org/Redoublet-website pull request #17
Opened 2023-03-20 21:20 UTC by Nightshades24

Laatste regels toegevoegd zoals

- Je mag alleen valide kaarten spelen
- Je kan doubleren en redoubleren
- Winnaar van de trick begint bij de volgende trick
- De speler links van degene die het bieden wint begint

2023-03-20 22:02 UTC, Toine1404 approved these changes

2023-03-21 07:44 UTC, MatthijsdeHeus commented
Er is een "open test board" knop in het menu die naar de het test board gaat. Hiervoor zat deze bij Random Board -> Play Alone. 
Dat is niet in jouw commits gebeurd maar wel handig om nu te fixen, welke van de 2 willen we hier gebruiken?

2023-03-21 07:45 UTC, MatthijsdeHeus commented on Redoublet-backend/Redoublet-backend/Models/Trick.cs
> +        public Suit? Suit { get; set; }
Wat betekend suit hier? Trump?
Mogelijk nog een comment plaatsen

2023-03-21 07:46 UTC, MatthijsdeHeus commented on Redoublet-backend/Redoublet-backend/Models/Trick.cs
> +            Suit = null;
Aangezien Suit nullable is, is dit echt nodig?

2023-03-21 07:49 UTC, MatthijsdeHeus commented on Redoublet-backend/Redoublet-backend/Services/BiddingService.cs
> +                    }
Wat gebeurd hier precies? Zou je nog een comment kunnen plaatsen?

2023-03-21 07:58 UTC, MatthijsdeHeus commented on Redoublet-backend/Redoublet-backend/Services/TrickService.cs
> +            if (canFollow && playedCard.Suit != gamestate.Trump && playedCard.Suit != gamestate.Tricks[gamestate.Tricks.Count - 1].Suit)
Klopt het dat canFollow waar moet zijn en dan returned hij de gamestate?

Het zou mij logisch klinken dat hij returned als de speler niet kan volgen

2023-03-21 08:00 UTC, MatthijsdeHeus commented on Redoublet-backend/Redoublet-backend/Models/Trick.cs
> +        public Suit? Suit { get; set; }
Nitpick: soms gebruiken we een witregel tussen properties in een model, soms niet. Lijkt me handig om dit uniform te hebben.

2023-03-21 08:30 UTC, MatthijsdeHeus requested changes
You should only be able to play the trump if you dont have the suit of the card that leads

2023-03-21 09:06 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Models/Trick.cs
> +            Suit = null;
Ik had het er voor de zekerheid in gelaten, maar dit is blijkbaar inderdaad niet nodig

2023-03-21 09:07 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Services/TrickService.cs
> +            if (canFollow && playedCard.Suit != gamestate.Trump && playedCard.Suit != gamestate.Tricks[gamestate.Tricks.Count - 1].Suit)
Ja, want hij returned de gamestate als de speler wel kan volgen, maar niet een kaart speelt waarmee hij de suit van die trick volgt

2023-03-21 09:15 UTC, Nightshades24 commented
- TestBoard is verwijderd
- Dit klopt niet inderdaad. Je mag doublen als het laatste bod door een tegenstander is gedaan
- Gefixt

2023-03-21 09:16 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Models/Trick.cs
> +        public Suit? Suit { get; set; }
We gebruiken dit volgens mij altijd hoor?

2023-03-21 09:17 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Models/Trick.cs
> +        public Suit? Suit { get; set; }
Ik heb bij de andere modellen evt een witregel toegevoegd

2023-03-21 10:04 UTC, Toine1404 commented
> a



> You should only be able to play the trump if you dont have the suit of the card that leads

trump suit of andere suit dan waarmee wordt geleid kunnen indd alleen gespeeld worden als de speler geen kaarten meer heeft in de suit waarmee wordt geleid

2023-03-21 11:20 UTC, MatthijsdeHeus commented on Redoublet-backend/Redoublet-backend/Services/BiddingService.cs
> +                foreach (Bid bid in gamestate.BidHistory)
Kan je niet gewoon een for loop doen die begint op het einde?

2023-03-21 11:20 UTC, MatthijsdeHeus commented on Redoublet-backend/Redoublet-backend/Services/TrickService.cs
> +            if (canFollow && playedCard.Suit != gamestate.Trump && playedCard.Suit != gamestate.Tricks[gamestate.Tricks.Count - 1].Suit)
Duidelijk

2023-03-21 11:32 UTC, MatthijsdeHeus requested changes
Nog een laatste paar bugs in double/redouble, voor de rest hele nice code!

2023-03-21 11:32 UTC, MatthijsdeHeus commented on Redoublet-backend/Redoublet-backend/Services/BiddingService.cs
> +            if (gamestate.BidHistory[gamestate.BidHistory.Count - 1].Suit != BiddingSuit.Double && gamestate.BidHistory[gamestate.BidHistory.Count - 3].Suit != BiddingSuit.Double)
Er gaan nog een paar dingen niet helemaal goed met redouble, dit is namelijk een bidding history die ik kan genereren:

- Club1
- Spade1
- Diamond2
- Pass
- Double
- Heart6
- Spade6
- Redouble
- Double
- Pass
- Diamond7
- Double
- Redouble
- Double
- Redouble
- Pass
- Redouble

2023-03-21 11:42 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Services/BiddingService.cs
> +                foreach (Bid bid in gamestate.BidHistory)
Kan zeker

2023-03-21 12:29 UTC, merged