Opzetten Google Cloud
Redoublet-org/Redoublet-website pull request #19
Opened 2023-03-26 20:48 UTC by MatthijsdeHeus

- CI/CD pipeline voor de Redoublet website

Niet alles voor deze PR is in de code te zien, zie ook https://console.cloud.google.com/cloud-build/triggers?authuser=1&project=redoublet-site

2023-03-27 09:39 UTC, Koekiemonster69 requested changes

2023-03-27 09:39 UTC, Koekiemonster69 commented on Redoublet-backend/Redoublet-backend/Program.cs
> +            .WithOrigins("https://redoublet-site.web.app")
kleine nitpick:
In de example doen ze policy.WithOrigins("http://example.com",
                                                  "http://www.contoso.com")
miss nice als wij ook dat op die manier doen, dus beide url's in 1 .withOrigins();

2023-03-27 09:52 UTC, MatthijsdeHeus commented on Redoublet-backend/Redoublet-backend/Program.cs
> +            .WithOrigins("https://redoublet-site.web.app")
Ahh je hebt zeker gelijk, gefixed

2023-03-29 14:36 UTC, Koekiemonster69 approved these changes

2023-03-30 20:10 UTC, Nightshades24 commented
Hoe kan ik dit precies testen?

2023-03-30 20:11 UTC, Nightshades24 commented
Ook loop ik hier tegenaan
![image](https://user-images.githubusercontent.com/71764800/228953143-9517b64d-080c-48b3-8f34-4b98809f8311.png)

2023-03-31 07:49 UTC, MatthijsdeHeus commented
Je kan de code testen door hier op Run te drukken bij de trigger:
https://console.cloud.google.com/cloud-build/triggers?authuser=1&project=redoublet-site

Ook moet je inloggen met Christiaan's account

2023-04-03 16:47 UTC, Nightshades24 requested changes

2023-04-03 16:47 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Program.cs
> +app.Run("http://0.0.0.0:5000");
Ontbreekt newline aan einde file

2023-04-03 16:47 UTC, Nightshades24 commented on cloudbuild.yaml
> +    dir: 'Redoublet-frontend/Redoublet-frontend'
Ontbreekt newline aan einde file

2023-04-03 16:54 UTC, Nightshades24 requested changes

2023-04-03 16:54 UTC, Nightshades24 commented on cloudbuild.yaml
> +
Hier ontbreekt een newline aan het einde van de file

2023-04-03 16:56 UTC, MatthijsdeHeus commented
Cloudbuild.yaml verwijdert volgensmij automatisch de newline aan het einde.

2023-04-03 16:56 UTC, Nightshades24 approved these changes

2023-04-03 17:07 UTC, merged