Playable cards
Redoublet-org/Redoublet-website pull request #20
Opened 2023-04-03 15:33 UTC by Stayutazen

Feature 149 geïmplementeerd, playable bool toegevoegd aan cards en hiermee zowel de trickservice als gameview aangepast

2023-04-03 19:58 UTC, Koekiemonster69 approved these changes

2023-04-04 11:25 UTC, sebas42069 requested changes
kleine verandering nodig

2023-04-04 11:25 UTC, sebas42069 commented on Redoublet-backend/Redoublet-backend/Services/TrickService.cs
> +                        if (card.Suit != gamestate.Tricks[gamestate.Tricks.Count - 1].Suit)
je kunt nu geen kaarten spelen als je geen kaarten over hebt met de eerstgespeelde suit

2023-04-05 09:38 UTC, sebas42069 approved these changes
yes werkt nu goed

2023-04-05 09:41 UTC, merged