Calculate points
Redoublet-org/Redoublet-website pull request #21
Opened 2023-04-04 13:44 UTC by Nightshades24

Calculates points for rubber bridge

2023-04-04 15:09 UTC, Nightshades24 commented
Pull request closed, there extra stuff has to be added

2023-04-06 10:54 UTC, Toine1404 requested changes

2023-04-06 10:54 UTC, Toine1404 commented on Redoublet-frontend/src/views/GameView.vue
> +                    <button @click="calculatePoints()">Calculate Points</button>
meerdere keren op deze button klikken zorgt ervoor dat de punten nog een keer worden uitgerekend en worden toegevoegd aan de score.

2023-04-06 10:54 UTC, Toine1404 commented on Redoublet-backend/Redoublet-backend/Services/PointService.cs
nog een paar dingen die niet helemaal goed gaan. als ik op de site een contract voor 7 no trump aan neem bijvoorbeeld en ik zorg ervoor dat het team 5 undertricks krijgt dan worden er na afloop maar 50 punten opgeteld bij de tegenstander alsof er maar 1 undertrick was

2023-04-06 10:54 UTC, Toine1404 commented on Redoublet-backend/Redoublet-backend/Models/GameState.cs
> +        public int PartialPointsEW { get; set; }
tijdens het testen laten partial points niet de punten onder de line zien. kijkend naar een contract van 1 club waarbij uiteindelijk 2 overtricks worden gehaald undoubled en niet vulnerable. 
![image](https://user-images.githubusercontent.com/93553185/230355284-725a49ec-d49f-4767-8b78-95571c403290.png)

2023-04-06 10:54 UTC, Toine1404 commented on Redoublet-backend/Redoublet-backend/Services/PointService.cs
> +            }
er moet onderscheid worden gemaakt bij situaties waarbij een team wint in 2 of 3 games dit maakt of zij respectievelijk 700 of 500 punten krijgen. dit zie ik nu nog niet terug. Toch is het nu wel het geval dat rubberbridge niet geïmplementeerd hoeft te worden dus ik weet niet of het handig is om hier nu extra tijd in te steken.

2023-04-06 10:54 UTC, Toine1404 commented on Redoublet-backend/Redoublet-backend/Services/PointService.cs
volgens mij als ik het zo zag worden de punten niet goed uitgelezen uit de tabel. Het gaat dus al fout met under en overtricks. Misschien moet er hier een test case voor worden geschreven zodat je weet dat dit klopt.

2023-04-09 13:40 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Controllers/BridgeGameLogic.cs
> +                PartialPointsEW = partialPointsEW,
Elke keer als de kaarten geshuffeld worden (dus wanneer op die knop gedrukt wordt) wordt er een nieuwe gamestate aangemaakt waarbij de kaarten over de spelers verdeeld zijn. De eerste keer is er natuurlijk nog geen en is gamestate dus "null". Daarom kan hij bij de nieuwe gamestate niet altijd de punten overnemen van de oude gamestate, want de eerste keer is er geen oude gamestate. 
Dit is wat er gebeurd, en leek mij ook de beste manier om het te doen, maar als je een suggestie hebt hoe dit beter kan hoor ik het graag

2023-04-09 13:51 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Controllers/BridgeGameLogic.cs
> +        }
Lijkt met niet nodig om een comment bij te zetten gezien de functie letterlijk "CalculatePoints" heet en het me dus wel duidelijk lijkt dat dit een functie is die je kan aanroepen om de punten van een gamestate te berekenen.

EnableCors("policy") zorgt ervoor dat de functie door een andere site (namelijk de frontend) kan worden aangeroepen, dat is in elk geval hoe ik het begrijp. @MatthijsdeHeus kun jij dit bevestigen?
Voor meer info kun je [hier ](https://learn.microsoft.com/en-us/aspnet/web-api/overview/security/enabling-cross-origin-requests-in-web-api)kijken.

2023-04-09 13:54 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Database/FullScoringSheet.cs
> +    }
Mijn antwoord hierboven geldt ook voor deze comment

2023-04-09 13:55 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Services/BiddingService.cs
> +                gamestate.Contract.Denominator = gamestate.Contract.Denominator;
Ja, maar ik hoorde van Dina dat bij de officiële pbn notatie de term "Denominator" wordt gebruikt. Vandaar dat deze ook in onze code wordt gebruikt.

2023-04-09 13:58 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Services/BiddingService.cs
> +
Als er gedoubled of redoubled wordt (in dit geval gedoubled), wordt de risk van de gamestate op "Doubled" gezet, om dus aan te geven dat er gedoubled is. Ik heb de naam van "gamestate.Doubled" nu vervangen naar "gamestate.Risk".

2023-04-09 14:01 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Services/PointService.cs
> +            Side side = gamestate.Contract.Side;
Dat is inderdaad een betere naam

2023-04-09 14:04 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Services/PointService.cs
> +            int rowNR = 0;
Als je naar onder scrollt zie je dat daar wel degelijk het rowNR wordt berekend, en ook op welke manier, waaraan dus af te leiden valt wat het betekent, omdat dit in een overzichtelijke switch staat.
![image](https://user-images.githubusercontent.com/71764800/230777309-0003f37a-1c5e-4492-bbbc-08bdd01475fa.png)
rowNR moet aan het begin al een waarde meekrijgen, omdat de switch geen default case bevat, waardoor hij anders een exception geeft. Door hem aan het begin 0 mee te geven wordt dit voorkomen.

2023-04-09 14:04 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Services/PointService.cs
> +            int rowNR = 0;
Mocht je het hier overigens alsnog niet mee eens zijn hoor ik het graag

2023-04-09 14:06 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Services/PointService.cs
> +            if (amountOfTricks >= gamestate.Contract.OddTricks)
Correct. Deze naam/implementatie komt niet vanuit mij, maar vanuit de code voor het importeren en exporteren van een pbn en ik geloof dat dit een officiële notatie is.

2023-04-09 14:09 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Services/PointService.cs
> +            if (amountOfTricks >= gamestate.Contract.OddTricks)
Ik heb de code nu (hopelijk) wat verduidelijkt.

2023-04-09 14:09 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Models/Bid.cs
>      }
Nee, want vulnerable heeft niks met bieden te maken, en dit wel.

2023-04-09 14:10 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Services/TrickService.cs
> +                }
Hoe dan?

2023-04-09 14:12 UTC, Nightshades24 commented on Redoublet-frontend/src/views/GameView.vue
> +                    <button @click="calculatePoints()">Calculate Points</button>
Dat is niet erg gezien de button natuurlijk maar tijdelijk is, en alleen voor debuggen/testen wordt gebruikt.

2023-04-09 14:56 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Services/PointService.cs
Klopt, ik was vergeten de 6 tricks mee te rekenen die je sowieso moet halen voor je contract. Als het goed is heb ik het nu gefixt.

2023-04-09 14:57 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Models/GameState.cs
> +        public int PartialPointsEW { get; set; }
Dit zou nu gefixt moeten zijn, nu ik de 6 tricks die je sws bij een contract moet halen meereken

2023-04-09 14:59 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Services/PointService.cs
> +            }
Klinkt niet echt alsof het veel tijd zou kosten, dus hoe werkt het dan precies met 700 of 500 punten? Dat wanneer je in 2 games 700 punten krijgt en in 3 games 500 ofzo? Dit zou ik namelijk in een paar minuten kunnen fixen

2023-04-09 15:02 UTC, Nightshades24 commented on Redoublet-frontend/src/views/GameView.vue
> +                    <button @click="calculatePoints()">Calculate Points</button>
Heb nu wel aangepast dat je alleen op de knop kan drukken als de gamestate in de points fase zit.

2023-04-11 11:20 UTC, Toine1404 commented on Redoublet-backend/Redoublet-backend/Services/TrickService.cs
> +                }
deze site geeft een aantal suggesties, de eerste met inverse if statements zou kunnen. https://softwareengineering.stackexchange.com/questions/47789/how-would-you-refactor-nested-if-statements

2023-04-11 11:24 UTC, Toine1404 commented on Redoublet-backend/Redoublet-backend/Services/PointService.cs
> +            }
ja dit klopt, je speelt best out of 3 rondes, win je in 2 rondes krijg je 700 punten, win je in 3 rondes (bijv. doordat het andere team een ronde wint in ronde 1 of 2) dan wint het team die de rubber wint (best out of 3) 500 punten

2023-04-11 11:56 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Services/PointService.cs
> +            }
Oke, heb dit gefixt

2023-04-11 11:58 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Services/PointService.cs
> +            }
Heb het geïmplementeerd

2023-04-11 12:03 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Services/TrickService.cs
> +                }
Dit beter?
![image](https://user-images.githubusercontent.com/71764800/231156885-218572b0-05bf-4b70-829e-687869909308.png)

2023-04-15 15:30 UTC, Koekiemonster69 requested changes
Ik neem aan dat je t op deze manier (een sheet waarin je de score kan opzoeken in plaats van een formule die de score direct uitrekent) hebt gedaan omdat we die scoring table al van de opdrachtgever hebben gekregen. Echter is dit zoals Toine heeft gezegd een beetje meer moeite voor anderen om te zien of alles klopt (bijvoorbeeld de 'magic numbers' in de switch case van PointService line 90).

Ik denk dat t voor dit soort back-end onderdelen nice zou zijn als we automatische tests zouden schrijven, zodat we 100% zeker weten dat t klopt, en ook dat we makkelijk kunnen kijken of er niks hiervan breekt als we nieuwe code toevoegen. Ben benieuwd wat jij en de rest van ons groepje daarover denken.

Voor de rest wel clean code, maar ik kon moeilijk testen of de implementatie correct was, want bij mij ging ie niet over naar de scoring fase als alle tricks gespeeld zijn, en die calculate score kun je nu alleen klikken in die fase, dus daarom voor nu nog niet geapproved.

![image](https://user-images.githubusercontent.com/74185498/232234242-da19aeaa-f95c-4965-8d46-bface0617c29.png)

2023-04-15 15:30 UTC, Koekiemonster69 commented on Redoublet-backend/Redoublet-backend/Models/Bid.cs
>      }
Is dit eigenlijk niet hetzelfde als wat er eerst stond (als in, is het niet zo dat als je undoubled niet specificeert, dat ie dan automatisch start op 0, of doe je dit gewoon om t duidelijker te maken?)

2023-04-15 15:30 UTC, Koekiemonster69 commented on Redoublet-backend/Redoublet-backend/Models/GameState.cs
> +        public int PointsBelowLineNS { get; set; }
De enige reden dat PointsBelowLine berekenen uberhaupt nodig is, is omdat het niet duidelijk was dat we duplicate bridge gaan doen, en niet rubber bridge (als ik het goed zeg), toch, want in principe is in dat duplicate bridge toch zo dat jouw team het aantal punten wint, wat het andere team verliest, en vice versa toch? Want in dat geval is het denk ik wel nice om overal ook die pointsbelowline weg te halen.

2023-04-15 15:30 UTC, Koekiemonster69 commented on Redoublet-backend/Redoublet-backend/Models/Player.cs
>      }
Netjes dat je West bovenaan zet, maar wederom, zijn de nummers dan nog nodig?

2023-04-15 15:30 UTC, Koekiemonster69 commented on Redoublet-backend/Redoublet-backend/Models/StartGameRequest.cs
> +        public GameState? Gamestate { get; set; }
Zou je uit willen leggen hoe zo'n ? operator werkt, want ik snap in dit geval niet helemaal wat het altrenatief is als je geen gamestate kan krijgen?

2023-04-15 15:30 UTC, Koekiemonster69 commented on Redoublet-backend/Redoublet-backend/Services/TrickService.cs
> +            if (!(gamestate.Tricks[gamestate.Tricks.Count - 1].PlayedCards.Count == 4 && gamestate.Tricks.Count <= 13))
Dit vat ik niet zo, als de trick nog niet finished is wil je toch juist een kaart kunnen spelen?

2023-04-15 15:30 UTC, Koekiemonster69 commented on Redoublet-backend/Redoublet-backend/Services/TrickService.cs
> +            if (!(gamestate.Tricks[gamestate.Tricks.Count - 1].PlayedCards.Count == 4 && gamestate.Tricks.Count <= 13))
oh laat maar, dit is voor als je een kaart hebt gespeeld, ik vat m

2023-04-15 15:30 UTC, Koekiemonster69 commented on Redoublet-backend/Redoublet-backend/Services/TrickService.cs
> +            // If not last trick, add new trick
Hier doe je twee keer hetzelfde, of lijkt dat maar zo?

2023-04-19 12:49 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Models/Player.cs
>      }
Eigenlijk niet, maar kunnen er voor de zekerheid bij blijven staan.

2023-04-19 13:19 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Models/StartGameRequest.cs
> +        public GameState? Gamestate { get; set; }
Dus ik heb dit nu aangepast en het vraagteken weggehaald

2023-04-19 14:56 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Models/StartGameRequest.cs
> +        public GameState? Gamestate { get; set; }
De "?" operator zorgt ervoor dat de variabele nullable wordt, dus dat deze "null" kan zijn. Bij een startgamerequest wil je dat gamestate "null" kan zijn. Als je hem namelijk de eerste keer aanroept is gamestate nog null en moet hij de eerste aanmaken. Als je hem echter later aanroept geeft hij de oude gamestate mee zodat hij de punten bijhoud. Daarom moet deze in dit geval nullable zijn.

2023-04-19 15:24 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Models/GameState.cs
> +        public int PointsBelowLineNS { get; set; }
Ik heb het aan Toine gevraagd, hij zegt dat het zo prima werkt, maar PointsBelowLine zou inderdaad weg kunnen omdat we geen rubberbridge spelen. Echter mochten ze later dit nog willen implementeren kan het zo makkelijk, dus is het niet echt erg.

2023-04-20 12:07 UTC, Koekiemonster69 requested changes
Die calculate points werkt bij mij nog steed niet man

2023-04-24 10:30 UTC, Koekiemonster69 approved these changes
Heelmaal goed!

2023-04-24 10:31 UTC, merged