Feature 172 x unit points
Redoublet-org/Redoublet-website pull request #28
Opened 2023-04-25 12:51 UTC by Koekiemonster69

De laatste test is eruitgecomment, ik liep vast op het deserializen van JSON objecten, dit gebeurt nu namelijk volgens mij automatisch in de API, maar ik weet niet hoe je die vanuit de back-end moet aanroepen, dus hiervoor komt later nog een cypress test

2023-04-26 11:04 UTC, sebas42069 requested changes

2023-04-28 14:36 UTC, Koekiemonster69 commented on Redoublet-backend/BackendTesting/BiddingTests.cs
> +        public void CanNotPassAsFirstMove()
Heb m weggehaald!

2023-05-04 01:20 UTC, Stayutazen requested changes
De tests zien er over het algemeen goed uit! Nog een algemeen vraagje, ik zie dat je bidding tests hebt geschreven in deze branch (feature-168) maar de PR staat open voor points testen (feature-172)?

2023-05-04 01:20 UTC, Stayutazen commented on Redoublet-backend/BackendTesting/BiddingTests.cs
> +        }
Misschien een test toevoegen dat wanneer de eerste 4 bids een pass zijn het spel opnieuw begint met nieuwe kaarten?

2023-05-04 01:20 UTC, Stayutazen commented on Redoublet-backend/BackendTesting/BiddingTests.cs
> +        }
Misschien kun je ook een test toevoegen dat je alleen mag doubleren als het gaat om een bid van het andere team? Weet niet hoe nodig het is (bijvoorbeeld noord die bied, oost passed en zuid mag nu niet doubleren aangezien het laatste bod van noord kwam)

2023-05-04 09:58 UTC, Koekiemonster69 commented on Redoublet-backend/Redoublet-backend/Services/BiddingService.cs
> +                    return gameState;
mmh ja je hebt gelijk, ik had inspiratie geput hieruit: 
![image](https://user-images.githubusercontent.com/74185498/236172371-aad20781-0506-4e6d-9504-e0e49f34f2b6.png)
dat is wat in main staat, maar dat klopt dan idd niet, zal t weghalen

2023-05-04 10:06 UTC, Koekiemonster69 commented on Redoublet-backend/BackendTesting/BiddingTests.cs
> +        }
goeie, ik zal dit nu gewoon implementeren met een if (true) en dan later kunnen we kijken per gamemode wat we willen dat er gebeurd

2023-05-07 18:49 UTC, Koekiemonster69 commented
> De tests zien er over het algemeen goed uit! Nog een algemeen vraagje, ik zie dat je bidding tests hebt geschreven in deze branch (feature-168) maar de PR staat open voor points testen (feature-172)?

Ja klopt, mb, ik heb wat dingetjes onhandig gedaan. Ik ben begonnen aan feature-168, de bidding tests, maar heb die om de één of andere reden "feature 172: points" genoemd, geen idee waarom haha. Vervolgens kwam ik erachter dat je om deze tests te schrijven eerst xUnit moet toevoegen aan de solution. Dat heb ik dus gedaan, en kwam er pas toen ik klaar was achter dat dit toevoegen een aparte taak (feature 174) is. Feature 172 moet dus nog gedaan worden door iemand!

2023-05-07 21:18 UTC, sebas42069 commented on Redoublet-backend/BackendTesting/BiddingTests.cs
> +            Assert.False(firstCardBefore.Suit == firstCardAfter.Suit && firstCardBefore.Value == firstCardAfter.Value);
heeele kleine kans, maar het kan toch wel gewoon dat na een reset je wel dezelfde eerste kaart hebt?

2023-05-08 08:42 UTC, Koekiemonster69 commented on Redoublet-backend/BackendTesting/BiddingTests.cs
> +            Assert.False(firstCardBefore.Suit == firstCardAfter.Suit && firstCardBefore.Value == firstCardAfter.Value);
ja klopt, ik zal tzelfde doen voor de tweede en derde kaart, dan is de kans denk ik klein genoeg

2023-05-09 11:25 UTC, Stayutazen approved these changes

2023-05-09 12:41 UTC, merged