Feature 196 oplevering website
Redoublet-org/Redoublet-website pull request #31
Opened 2023-05-04 10:00 UTC by sebas42069

Alles van pixi zit hierin. Als het goed is scaled alles nu naar de grootte van je monitor en window. Het behoudt een ratio van 16:9. Als je het in de browser viewed door een ipad scherm dan begint hij ingezoomd, maar dat gebeurt niet als je 'auto-adjust zoom' uitzet? Ik weet niet of dit gewoon een browser ding is en dat het er goed uitziet op een echte ipad.

Aan het einde van een spel krijg je je eigen punten te zien, en als je het contract had gewonnen het verschil tussen je behaalde slagen en het contract. Ook kun je op de knop 'analyseren van spel' drukken en wordt de canvas voor nu vervangen met een een tabel van de dds analyse.

2023-05-05 14:26 UTC, Stayutazen requested changes
Pixi ziet er echt super goed uit! Lijkt ook goed te scalen bij zowel mijn monitor als mijn laptop scherm! Qua code alleen nog een paar kleine aanpassingen, en ik heb niet veel kunnen commenten op sommige files in de backend aangezien die van mij af kwamen dus kijk hier zelf nog maar kritisch naar :)

2023-05-05 14:26 UTC, Stayutazen commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +    }
er is ook een currentGamestate.value.dummy variabele waar je direct de dummy uit kunt halen

2023-05-05 14:26 UTC, Stayutazen commented on Redoublet-frontend/src/views/GameView.vue
> +}
Vraagje, maar waar gebruikt GameView deze functies voor? Als het goed is zijn het allemaal precies dezelfde functies als PixiComponent en staat het er dus dubbelop in. Willen we dit spreiden dat PixiComponent deze functies gebruikt, of alle functies in PixiComponent houden? Denk dat als we bv PixiComponent kiezen al deze functies hier uit kunnen en vice versa?

2023-05-05 23:40 UTC, Toine1404 requested changes
ziet er opzich al goed uit! hier en daar is de uitstraling nog wat ruw en kan wat refinement gebruiken om het spel ook duidelijker te maken voor de spelers

2023-05-05 23:40 UTC, Toine1404 commented on Redoublet-frontend/src/views/GameView.vue
> +
remove whiteline

2023-05-05 23:40 UTC, Toine1404 commented on Redoublet-frontend/src/views/GameView.vue
> +
remove whiteline

2023-05-05 23:40 UTC, Toine1404 commented on Redoublet-frontend/src/views/GameView.vue
> +}
ik denk dat het indd handig is om alle functies op een centraal punt te houden

2023-05-05 23:40 UTC, Toine1404 commented on Redoublet-frontend/src/views/PlayedGames/AnalysisView.vue
> +  padding-right: 0;
ipv margin-left en margin right kun je ook margin: top right bottom left, gebruiken of nog korter: margin: top/bottom left/right. hetzelfde geldt voor padding

2023-05-05 23:40 UTC, Toine1404 commented on Redoublet-frontend/src/views/PlayedGames/AnalysisView.vue
> +  margin-left: 10px;
is het slim om deze in pixels te laten staan ivm responsiveness?

2023-05-05 23:40 UTC, Toine1404 commented on Redoublet-frontend/src/views/PlayedGames/AnalysisView.vue
nog een paar opmerkingen in het algemeen. Ik weet niet waar ze precies bij horen dus ik laat ze hier achter. 
1. bij het laten zien van het resultaat wordt de laatste slag die is gespeeld niet meegenomen in het scherm links boven.
2.  bij het laten zien van het resultaat kan er miss iets meer context worden gegeven bij de getallen die worden laten zien.
3. tijdens het laten zien van het resultaat zijn Noord Zuid West en Oost nogsteeds zichtbaar en staan op rare plaatsen.

Het gaat hierbij vooral om het 2e puntje maar als de andere twee snel te fixen zijn is dit alleen maar mooi meegenomen. het plaatje hieronder is ter referentie

![image](https://user-images.githubusercontent.com/93553185/236584260-72546fdf-ea1a-4e70-b334-40e081ab0103.png)

2023-05-05 23:40 UTC, Toine1404 commented on Redoublet-frontend/src/views/PlayedGames/AnalysisView.vue
bij het laten zien van de DDS analyse is er voor de gebruiker geen een mogelijkheid om terug te gaan en nog een spel te spelen(ook de terug knop in de browser kon ik niet aanklikken)

![image](https://user-images.githubusercontent.com/93553185/236584360-a0f199b4-e671-44b6-af78-372d618345ba.png)

2023-05-05 23:40 UTC, Toine1404 commented on Redoublet-frontend/src/views/PlayedGames/AnalysisView.vue
tijdens het bieden blijven de biedingen die hij niet kan doen dezelfde kleur. een speler kan deze ook aanklikken en er wordt dan gevraagd of een speler dit bod wil doen, het gevolg is dat er vervolgens niks gebeurd. miss deze grijs maken en/of non-clickable?

2023-05-05 23:40 UTC, Toine1404 commented on Redoublet-frontend/src/views/PlayedGames/AnalysisView.vue
als je vaak op shuffle cards klikt of er op klikt op het moment dat de computer een zet moet doen is het gevolg dat de computer voor jou een of meerdere zetten voor jou gaat spelen. Ik heb op deze manier een heel spel op 3 kaarten na kunnen spelen zonder ook maar 1 zet te doen (dat was eigenlijk best wel ziek lol) De rede waarom dit gebeurd is omdat de opdracht om een nieuw spel aan te maken sneller verloopt dan de aanroepen op robo bridge. deze staan nog gequeued en worden in het nieuwe spel uitgevoerd

2023-05-05 23:40 UTC, Toine1404 commented on Redoublet-frontend/src/views/PlayedGames/AnalysisView.vue
je kan tijdens het bieden op boden klikken die andere spelers hebben gedaan bij hun kant en vervolgens wordt het gezien alsof je dat bod wilt uibrengen. deze zijn dus nog klikbaar wat niet helemaal de bedoeling is

2023-05-05 23:40 UTC, Toine1404 commented on Redoublet-frontend/src/views/PlayedGames/AnalysisView.vue
de bied conventies van de bots worden niet weergegeven. dit is miss wel handig voor de "ervare" bridge spelers die Christiaan heeft uitgenodigd om het spel mee te spelen.

2023-05-06 13:24 UTC, sebas42069 commented on Redoublet-backend/Redoublet-backend/Controllers/BridgeGameLogic.cs
> +            }
shuffle cards knop is eruit gehaald, en is vervangen door een onetime knop start spel

2023-05-06 13:27 UTC, sebas42069 commented on Redoublet-frontend/src/views/PlayedGames/AnalysisView.vue
dat is logica dat in de backend gedaan zou moeten worden

2023-05-06 13:27 UTC, sebas42069 commented on Redoublet-frontend/src/views/PlayedGames/AnalysisView.vue
de shuffle cards knop is weggehaald nadat het spel begint

2023-05-06 14:03 UTC, sebas42069 commented on Redoublet-frontend/src/views/PlayedGames/AnalysisView.vue
ik heb geen idee waar ik deze informatie vandaan zou halen

2023-05-06 14:04 UTC, sebas42069 commented on Redoublet-frontend/src/views/PlayedGames/AnalysisView.vue
dit is gefixt

2023-05-06 14:05 UTC, sebas42069 commented on Redoublet-backend/Redoublet-backend/Models/ExportPBN.cs
> +
oke

2023-05-06 14:06 UTC, sebas42069 commented on Redoublet-backend/Redoublet-backend/Program.cs
als het goed is wel

2023-05-06 14:06 UTC, sebas42069 commented on Redoublet-backend/Redoublet-backend/Models/StartGameRequest.cs
> +﻿ namespace Redoublet.Backend.Models
gedaan

2023-05-06 14:06 UTC, sebas42069 commented on Redoublet-backend/Redoublet-backend/Models/ExportPBN.cs
> +";
gedaan

2023-05-06 14:06 UTC, sebas42069 commented on Redoublet-backend/Redoublet-backend/Models/ExportPBN.cs
> +";
done

2023-05-06 14:06 UTC, sebas42069 commented on Redoublet-backend/Redoublet-backend/Models/ExportPBN.cs
> +
done

2023-05-06 14:07 UTC, sebas42069 commented on Redoublet-backend/Redoublet-backend/Models/ExportPBN.cs
done

2023-05-06 14:07 UTC, sebas42069 commented on Redoublet-backend/Redoublet-backend/Models/ExportPBN.cs
> +
done

2023-05-06 14:07 UTC, sebas42069 commented on Redoublet-backend/Redoublet-backend/Connected Services/ServiceReference1/Reference.cs
> +//------------------------------------------------------------------------------
geen idee, heb ik niet gedaan

2023-05-06 16:50 UTC, sebas42069 commented on Redoublet-backend/Redoublet-backend/Services/BiddingService.cs
> +                else if (gamestate.Auction[gamestate.Auction.Count - 1].ContractRisk == Risk.Redoubled) possibleDeclarer = (Side)(((int)gamestate.CurrentPlayer + 2) % 4);
vind ik niet echt nodig met de comment die erbij staat

2023-05-06 16:52 UTC, sebas42069 commented on Redoublet-backend/Redoublet-backend/Services/BiddingService.cs
> +                //gamestate.OpeningLeader = gamestate.CurrentPlayer;
comments weggehaald

2023-05-06 16:59 UTC, sebas42069 commented on Redoublet-frontend/src/views/PlayedGames/AnalysisView.vue
> +  margin-left: 10px;
ziet er prima uit op verschillende schermen

2023-05-06 17:27 UTC, sebas42069 commented on Redoublet-backend/Redoublet-backend/Services/RoboBridgeService.cs
> +            Console.WriteLine(pbn);
volgens mij niet

2023-05-06 17:31 UTC, sebas42069 commented on Redoublet-backend/Redoublet-backend/Services/RoboBridgeService.cs
> +        }
snap ik ook niet helemaal

2023-05-06 17:32 UTC, sebas42069 commented on Redoublet-backend/Redoublet-backend/Services/RoboBridgeService.cs
> +                _ => throw new InvalidDataException("Enum Side does not supported instance " + s),
gefixt

2023-05-06 17:34 UTC, sebas42069 commented on Redoublet-frontend/src/views/PlayedGames/AnalysisView.vue
> +  padding-right: 0;
done

2023-05-06 17:37 UTC, sebas42069 commented on Redoublet-frontend/src/views/PlayedGames/AnalysisView.vue
alle drie de punten zijn gefixt

2023-05-06 17:38 UTC, sebas42069 commented on Redoublet-frontend/src/views/PlayedGames/AnalysisView.vue
Er is een start nieuw spel knop boven de tabel toegevoegd.

2023-05-06 17:39 UTC, sebas42069 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +    }
yes die gebruik ik nu

2023-05-06 17:39 UTC, sebas42069 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +app.stage.addChild(shuffleText);
done

2023-05-06 17:40 UTC, sebas42069 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +// app.stage.addChild(analyseTest);
done

2023-05-06 17:40 UTC, sebas42069 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +//app.stage.addChild(backButton);
done

2023-05-06 17:41 UTC, sebas42069 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +        //biddingBox.getChildAt(i * 5 + j).scale.set(0.8)
done

2023-05-06 17:41 UTC, sebas42069 commented on Redoublet-backend/Redoublet-backend/Services/BiddingService.cs
> +                //gamestate.OpeningLeader = gamestate.CurrentPlayer;
done

2023-05-06 17:42 UTC, sebas42069 commented on Redoublet-backend/Redoublet-backend/Controllers/BridgeGameLogic.cs
>  using System.Text.Json;
done

2023-05-06 17:50 UTC, sebas42069 commented on Redoublet-backend/Redoublet-backend/Controllers/BridgeGameLogic.cs
> +            return ExportPBN.DDSDealToString(gameState);
done

2023-05-06 17:51 UTC, sebas42069 commented on Redoublet-backend/Redoublet-backend/Models/ExportPBN.cs
> +        }
functie weggehaald

2023-05-06 17:51 UTC, sebas42069 commented on Redoublet-frontend/src/views/GameView.vue
> +}
done

2023-05-08 10:06 UTC, Toine1404 commented on Redoublet-backend/Redoublet-backend/Services/BiddingService.cs
> +                else if (gamestate.Auction[gamestate.Auction.Count - 1].ContractRisk == Risk.Redoubled) possibleDeclarer = (Side)(((int)gamestate.CurrentPlayer + 2) % 4);
ik zie nu dat de if statement minder groot is dan gedacht. Deze indruk werd gewekt doordat niet de stijl die wij gebruiken voor if statements wordt gebruikt.  herschrijf deze naar de volgende vorm:

 if (gamestate.Auction[gamestate.Auction.Count - 1].ContractRisk == Risk.Doubled)
                {
                    possibleDeclarer = (Side)(((int)gamestate.CurrentPlayer + 3) % 4);
                }

2023-05-08 10:10 UTC, Toine1404 commented on Redoublet-backend/Redoublet-backend/Services/RoboBridgeService.cs
> +        }
Ik weet niet wie het heeft geschreven. probeer dit anders opgehelderd te krijgen bij degene die dit heeft geschreven. De rede waarom ik dit vraag is omdat dit blok code nog niet in main zit. Ik ga er dan gwn kritisch naar kijken dus vandaar

2023-05-08 13:05 UTC, sebas42069 commented on Redoublet-backend/Redoublet-backend/Services/RoboBridgeService.cs
> +        }
conclusie: RoboBridge is kut, en soms moet je meerdere requests doen om een antwoord te krijgen

2023-05-08 15:22 UTC, Stayutazen approved these changes
Ziet er goed uit nu

2023-05-08 15:23 UTC, merged