Unit tests voor TrickService
Redoublet-org/Redoublet-website pull request #52
Opened 2023-05-18 17:18 UTC by Stayutazen

Unit tests voor tricks

2023-05-25 10:54 UTC, Koekiemonster69 approved these changes
Hele nette code dina!

2023-05-25 10:54 UTC, Koekiemonster69 commented on Redoublet-backend/BackendTesting/TricksTests.cs
> +            Assert.Equal(result.Tricks[0].Suit, expected);
Nitpick: ff expected en actual omdraaien

2023-05-29 08:37 UTC, Koekiemonster69 submitted a review, later dismissed

2023-05-31 13:34 UTC, MatthijsdeHeus requested changes
Mooie tests!

2023-05-31 13:34 UTC, MatthijsdeHeus commented on Redoublet-backend/BackendTesting/TricksTests.cs
> +        //Cards of all players
Nitpick: add a space after the // of all the comments

2023-05-31 13:34 UTC, MatthijsdeHeus commented on Redoublet-backend/BackendTesting/TricksTests.cs
> +
Nitpick: remove blank line

2023-05-31 13:34 UTC, MatthijsdeHeus commented on Redoublet-backend/BackendTesting/TricksTests.cs
> +            var expected = card.Suit;
Nitpick: add some blank lines

2023-05-31 13:34 UTC, MatthijsdeHeus commented on Redoublet-backend/BackendTesting/TricksTests.cs
> +            GameState gamestate = new GameState
Kunnen we dit random maken?

2023-05-31 23:18 UTC, Stayutazen commented on Redoublet-backend/BackendTesting/TricksTests.cs
> +            GameState gamestate = new GameState
Ik denk persoonlijk niet dat het veel zou toevoegen aan de tests(?). In alle andere testen zijn ook standaard gamestate waardes gebruikt en ik gebruik in sommige tests ook wel het feit dat ik weet welke kaart van welke player is

2023-05-31 23:21 UTC, Stayutazen commented on Redoublet-backend/BackendTesting/TricksTests.cs
> +            var expected = card.Suit;
Sorry maar waar precies? na '{' ? En bij elke testfunctie?

2023-06-04 16:29 UTC, MatthijsdeHeus approved these changes

2023-06-05 07:48 UTC, Koekiemonster69 approved these changes
priem

2023-06-05 10:18 UTC, merged