Feature 253 single player uitleg knop
Redoublet-org/Redoublet-website pull request #54
Opened 2023-05-22 17:16 UTC by Stayutazen

Als er op een speler's bod wordt geklikt opent dit nu een box met de speler's uitleg voor dit bod. Dubbelklikken veroorzaakt geen probleem en het spel begint niet met spelen tot je deze box hebt weggeklikt.

2023-05-25 11:38 UTC, Koekiemonster69 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +            if(!promptOpen){
De robot bied nu nog wel als de prompt er is. Verder heeft deze line nog niet heel veel nut, want de biedhistory verdwijnt nu als men begint met spelen.

2023-05-25 11:45 UTC, Koekiemonster69 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +            bid('Clubs', 0);
Hier zou wel een commentje bij mogen, waarom je clubs 0 bied

2023-05-25 11:51 UTC, Koekiemonster69 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +                wBids.push([currentGamestate.value.auction[j], j+1]);
Waarom is dit aangepast, door die bids van Club 0?

2023-05-25 14:21 UTC, Stayutazen commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +            bid('Clubs', 0);
Ik heb dit van Sebas overgenomen, maar ik dacht omdat je nooit 0 clubs kan bieden (ongeldig bod) en dus de backend de normale gamestate terug returned. Omdat de gamestate dus is veranderd gaat pixi opnieuw renderen en zo 'sluit' je de prompt. Maar omdat ik dit eigenlijk niet echt zeker weet vraag ik Sebas er wel naar

2023-05-25 14:23 UTC, Stayutazen commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +                wBids.push([currentGamestate.value.auction[j], j+1]);
Omdat RoboBridge vanuit de frontend wil weten op welke index de bid staat. Een BidSprite (wat eerst gebruikt werd voor bidhistory) bewaart de index van een kaart niet, nu gebruiken we een playerBidSprite (bidding history) en deze moet wel een index opslaan vandaar dat we nu j+1 (de index) ook erbij meegeven

2023-05-28 00:48 UTC, Stayutazen commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +    const promptTitle = new PIXI.Text(`${side}s uitleg voor bod ${amount}${suitToIcon[suit]}:`);
De 2e line is de output van robobridge dus eigenlijk niet veel aan te veranderen. Als het goed is weet Christiaan dit ook(?) Of bedoel je dat het mooier zou zijn als de eerste line ook in het Engels staat? Vond het een beetje raar aangezien de rest van het platform wel Nederlands is

2023-05-28 02:20 UTC, Stayutazen commented
> Eyo, ziet er op zich (voor zover pixi dat kan zijn) best wel goed uit, ik heb alleen nog een bug, als ik op andermans bid klik terwijl zij nog aan de beurt zijn, en ik daarna snel aan de beurt ben en op ok klik, bied ik iets, zonder dat ik de bid confirm. Beetje moeilijk om uit te leggen, maar ik hoop dat dit genoeg is om het te recreëren. Verder nog paar kleine vraagjes. Succes!

Het probleem kwam door het gebruiken van bid('Clubs', 0) om de gamestate te refreshen. Omdat we werken met asynchronous methods returnde het sluiten currentplayer Oost terwijl deze al veranderd was. Bij een veranderde gamestate wordt altijd gecheckt of robobridge aangeroepen kan worden. De code dacht dus dat Oost aan de beurt is terwijl het al Zuid's beurt was geworden en werd robobridge aangeroepen (maar werd vervolgens wel de geupdate gamestate waarin zuid de current player is doorgegeven). Ik zet nu gewoon handmatig alle verwijderde components terug en heb dit ook bij de prompt voor het bieden gedaan aangezien ik hieruit het idee had gehaald om bid('Clubs', 0) te gebruiken (voor het geval dit ook mis kan gaan). Test het vooral nog even ik heb er zelf geen last meer van gehad maar misschien is het probleem er nog!

2023-05-28 02:23 UTC, Stayutazen commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +    approveBG.width = Math.max(promptExplanation.width, promptTitle.width) + 40;
Yes! Components die children zijn van de app (als je wat verder in de code kijkt) kunnen gewoon statisch aangemaakt worden en toegevoegd worden aan de app. Later in de code wordt de app responsive gemaakt en zo dus ook alle children (zo blijven de verhoudingen altijd hetzelfde)

2023-05-29 08:59 UTC, Koekiemonster69 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +            if(!promptOpen){
mmh oke, maar dat doet ie nu nog niet right? hij gaat nu althans gewoon direct door lijkt t

2023-05-29 09:04 UTC, Koekiemonster69 approved these changes
goed bezig

2023-05-29 11:17 UTC, Stayutazen commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +            if(!promptOpen){
Oh huh bij mij niet?

2023-05-29 13:25 UTC, Koekiemonster69 submitted a review, later dismissed
👍

2023-05-29 14:04 UTC, Toine1404 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +    const promptTitle = new PIXI.Text(`${side}s uitleg voor bod ${amount}${suitToIcon[suit]}:`);
beter dan om of alles in het engels te doen of om North te vervangen door Noord

2023-05-29 14:35 UTC, Stayutazen commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +    const promptTitle = new PIXI.Text(`${side}s uitleg voor bod ${amount}${suitToIcon[suit]}:`);
Oh ik had niet eens door dat daar nog North's stond, ik pas dat dan wel aan!

2023-05-29 14:45 UTC, Toine1404 requested changes

2023-05-29 14:45 UTC, Toine1404 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +        setTimeout(() => robobid("SAYC"), 2000)
moeten deze SAYC ook niet vervangen worden door een variabele?

2023-05-29 14:45 UTC, Toine1404 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +                setTimeout(() => roboPlayCard("SAYC"), 2000)
zelfde voor deze?

2023-05-29 14:47 UTC, Stayutazen commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +        setTimeout(() => robobid("SAYC"), 2000)
Is gedaan in de branch feature 277 biedadvies (die heeft ook een nieuwere versie van de backend)

2023-05-29 14:50 UTC, Toine1404 submitted a review, later dismissed

2023-05-30 09:13 UTC, Toine1404 approved these changes

2023-05-30 09:25 UTC, merged