Feature 270 delay na slag
Redoublet-org/Redoublet-website pull request #56
Opened 2023-05-24 15:56 UTC by Stayutazen

Robobridge speelt een normaal spel met een delay van 2 seconden, ik heb het nu zo gemaakt dat robobridge aan het einde van een slag een delay van 5 seconden heeft. Ik weet niet of dit een fijne delay is dus probeer het vooral. (Zorgt er ook voor dat je langer de tijd hebt het schermpje met spel informatie zoals dummy en trump te lezen)
De speler / zijn dummy hebben nu ook een delay als ze aan de beurt zijn aan het einde van een trick, je kunt dan voor 5 seconden niet op je kaarten drukken. Ik gok dat de code hiervan veranderd moet worden als multiplayer ook in main zit (timeout zetten op de interactability van een kaart). Zodra multiplayer in main zit zal ik het mergen met deze branch

2023-05-25 12:42 UTC, Koekiemonster69 requested changes
Ziet er goed uit, twee dingetjes (1 is handig, 2 is optioneel):
1 De time-out numbers misschien ff in variabelen zetten voor makkelijkere tweaking
2 Op zich stoort de delay na de slag denk ik niet als je rustig zit te bridgen, maar wel als je zo snel mogelijk probeert bij de analyse pagina te komen, misschien zou t nice zijn dat er een debug optie is om de vertraging uit te zetten?

2023-05-25 15:13 UTC, Toine1404 requested changes
ziet er goed uit, paar schoonheids foutjes, maar voor de rest prima

2023-05-25 15:13 UTC, Toine1404 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +                console.log("end of trick")
moet deze console.log in de code blijven staan? het is een vrij dure operatie waar een gebruiker niks van zal terug zien

2023-05-25 15:13 UTC, Toine1404 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +            //Timeouts so players can't play a card right after the end of a trick
waarom nog de else in deze if statement (oprechte vraag want ik snap m niet helemaal haha)

2023-05-25 15:13 UTC, Toine1404 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +            }
fix indentation. raar dat de linter deze niet oppakt

2023-05-28 02:38 UTC, Stayutazen commented
> Ziet er goed uit, twee dingetjes (1 is handig, 2 is optioneel): 1 De time-out numbers misschien ff in variabelen zetten voor makkelijkere tweaking 2 Op zich stoort de delay na de slag denk ik niet als je rustig zit te bridgen, maar wel als je zo snel mogelijk probeert bij de analyse pagina te komen, misschien zou t nice zijn dat er een debug optie is om de vertraging uit te zetten?

Ik denk dat punt 2 al gefixt zou worden van punt 1? Als je wilt debuggen kun je de variabelen gewoon op 0 zetten

2023-05-28 02:39 UTC, Stayutazen commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +                console.log("end of trick")
Nope, vergeten weg te halen :)

2023-05-28 02:40 UTC, Stayutazen commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +            //Timeouts so players can't play a card right after the end of a trick
Goed dat je het zag!! Dit komt nog voort uit oude code. We wilden eerst andere functionaliteit hebben voor deze  gevallen maar dit is onderhand veranderd en de if statement is nooit samen gegooit!

2023-05-29 09:54 UTC, Koekiemonster69 approved these changes

2023-05-29 14:10 UTC, Toine1404 approved these changes
goed aangepast, wat eventueel in een latere versie van de site zou kunnen komen, is dat spelers zelf in een options menu de delay zouden kunnen aanpassen. miss zou dit nog een taak voor later kunnen zijn

2023-05-29 14:32 UTC, merged