Feature 277 biedadvies singleplayer
Redoublet-org/Redoublet-website pull request #61
Opened 2023-05-28 18:08 UTC by Stayutazen

Er is nu een biedadvies knop, als het jouw beurt is kun je deze gebruiken om advies te krijgen van robobridge

2023-05-29 13:27 UTC, Nightshades24 requested changes

2023-05-29 13:27 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Controllers/BridgeGameLogic.cs
>                  contract.Pass = false;
Gezien je contract alleen hier gebruikt is het netter om hier pas contract aan te maken en deze waarden gelijk in de constructor te zetten

2023-05-29 13:27 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Controllers/BridgeGameLogic.cs
>              return finalState;
Gezien je in deze if-else statement de finalState update en hem daarna returned kun je hem beter gelijk in de if else returnen. Dan hoef je ook geen finalState variabele aan te maken, maar kun je returnen wat uit de biddingservice komt.

2023-05-29 13:27 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Controllers/BridgeGameLogic.cs
> +            //Let the robot bid to see what choice it would've made
Nitpick: zet bij deze en de comments eronder een spatie tussen de ```//``` en de tekst

2023-05-29 13:27 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Controllers/BridgeGameLogic.cs
> +            return result;
Ook hier kan je de result variabele achterwege laten als je gelijk in de if-else returned. 

Nitpick: Zet ook overal een ```{ }``` set omheen vanwege code styling

2023-05-29 13:27 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Models/ExplainBidRequest.cs
> +        public int bidIndex { get; set; }
Nitpick: deze variabelen moeten met een hoofdletter beginnen. Zie [dit](https://learn.microsoft.com/nl-nl/dotnet/fundamentals/code-analysis/style-rules/naming-rules) voor meer info

2023-05-29 13:27 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Models/RobotRequest.cs
> +        public string convention { get; set; }
Nitpick: ook deze variabele moet met een hoofdletter beginnen

2023-05-29 13:27 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Services/RoboBridgeService.cs
> +            //When RoboBridge gives an error, try it 5 times before giving up (sometimes RoboBridge gives an error and a response for the exact same request)
Nitpick: zet ook hier een spatie tussen de ```//``` en de tekst

2023-05-29 13:27 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Services/RoboBridgeService.cs
> +            Task<Bid> bid = GetBid(pbn, convention, convention, seat, Scorings.scMP);
Forceert dit niet dat beide teams dezelfde conventie spelen? Zou je niet 2 variabelen willen gebruiken? En dan evt voor nu bij het aanroepen hier 2x dezelfde waarde invoeren. Pas dit ook op de plekken eronder aan.

2023-05-29 13:27 UTC, Nightshades24 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +            //Robot won't play yet if a prompt is still open
Nitpick: ook hier spatie

2023-05-29 13:27 UTC, Nightshades24 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +            //You can't open a prompt if another prompt is already opened (this check is due to the asynchronous roboExplainBid)
Nitpick: ook hier spatie :)

2023-05-29 13:27 UTC, Nightshades24 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +                roboExplainBid("SAYC", index).then(res => promptExplanation(suit, value, side, this.specialAction, res));
Nitpick: zet hier wat enters voor betere leesbaarheid

2023-05-29 13:27 UTC, Nightshades24 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +    //Sometimes robobridge doesn't give an explanation
Nitpick: ook hier spatie

2023-05-29 13:27 UTC, Nightshades24 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +    //Could also be a pass, double or redouble
Nitpick: ook hier spatie

2023-05-29 13:27 UTC, Nightshades24 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +    //specialAction = -1 when it's a normal bid
Nitpick: ook hier spatie

2023-05-29 13:27 UTC, Nightshades24 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +        //anything else is either a pass, double or redouble
Nitpick: ook hier spatie

2023-05-29 13:27 UTC, Nightshades24 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
>  //setting up the containers for the hands
Nitpick: ook hier spatie

2023-05-29 13:27 UTC, Nightshades24 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +//Bool to check if prompt is open, so it doesn't render a bidding or playing box in front of it
Nitpick: ook hier spatie

2023-05-29 13:27 UTC, Nightshades24 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
>  //display cards in the right positions
Nitpick: ook hier spatie

2023-05-29 15:49 UTC, Toine1404 requested changes
ziet er goed uit, 2 puntjes en meer niet.

2023-05-29 15:49 UTC, Toine1404 commented on Redoublet-backend/Redoublet-backend/Services/RoboBridgeService.cs
> +
![image](https://github.com/Redoublet-org/Redoublet-website/assets/93553185/29646977-7f6d-45da-8a38-308fb95655a2)
voor de eerste pass gaf robobridge een uitleg. voor de tweede niet meer en krijg ik een vraagteken. wat is handig om hiermee te doen?

2023-05-29 15:49 UTC, Toine1404 commented on Redoublet-backend/Redoublet-backend/Controllers/BridgeGameLogic.cs
probeer te kijken of je 253 hier nog in kan mergen voor de laatste veranderingen

2023-05-29 16:29 UTC, Stayutazen commented on Redoublet-backend/Redoublet-backend/Services/RoboBridgeService.cs
> +
Dit hoort bij feature 253, wat ik daar had gedaan is ik heb gezegd dat wanneer robobridge een "?" of "" returned er komt te staan "Geen uitleg". Kan je ook in die branch vinden :)

2023-05-29 17:48 UTC, Nightshades24 reviewed
Ziet er goed uit, heb geen aanmerkingen meer behalve de comments van de linter

2023-05-31 23:44 UTC, Stayutazen commented on Redoublet-backend/Redoublet-backend/Controllers/BridgeGameLogic.cs
Dit zit er nu in door het mergen van main :)

2023-05-31 23:45 UTC, Stayutazen commented
> Ziet er goed uit, heb geen aanmerkingen meer behalve de comments van de linter. Ook moet je main er nog in mergen, dus dan ook nog de knop aan multiplayer toevoegen, denk ik?

Main is gemerged! De knop aan multiplayer toevoegen is een andere feature en zou in een andere branch moeten gebeuren!

2023-06-01 13:09 UTC, Toine1404 requested changes

2023-06-01 13:09 UTC, Toine1404 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +    // specialAction = -1 when it's a normal bid
hoofdletter

2023-06-02 01:26 UTC, Stayutazen commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +    // specialAction = -1 when it's a normal bid
Is dat hier nodig? specialAction is de naam van de variabele...

2023-06-05 08:05 UTC, Toine1404 submitted a review, later dismissed

2023-06-05 09:00 UTC, Nightshades24 requested changes

2023-06-05 10:23 UTC, Stayutazen commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +        promptExplanation.text = `Reden: ${explanation}`;
Sorry ik snap niet wat je bedoelt?
const promptTitle = new PIXI.Text(`${sideToDutch[side]}s uitleg voor bod ${amount}${suitToIcon[suit]}:`);
is dat niet genoeg?

2023-06-05 10:28 UTC, Stayutazen commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
>          promptExplanation.text = explanation;
Snap hier ook niet helemaal wat je bedoelt

2023-06-05 10:53 UTC, Stayutazen commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +        promptExplanation.text = `Reden: ${explanation}`;
Ik snap nu wat je bedoelt. Ik denk zelf dat het teveel moeite zou kosten om de suit in de string te vinden en kunnen er mogelijk false positives uitkomen aangezien een suit aan de hand van 1 letter wordt aangeduid. Ik vind het ook een beetje buiten de scope vallen als ik dit voor zowel biedadvies als bieduitleg zou moeten doen. Ook vond christiaan zelf de uitleg prima maar als je dit graag wil doen kan ik er een taakje voor in Jira zetten.

2023-06-05 15:43 UTC, Stayutazen commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +        promptExplanation.text = `Reden: ${explanation}`;
Ik vind het zelf buiten de scope vallen van mijn PR. Ik snap de comment wel, maar vooral omdat het uniform zou moeten zijn voor zowel biedadvies als bieduitleg en mijn PR alleen over de implementatie van biedadvies met RoboBridge gaat. We kunnen het er nog wel over hebben of dit een apart taakje zou kunnen worden of niet

2023-06-05 19:38 UTC, Nightshades24 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +        promptExplanation.text = `Reden: ${explanation}`;
Ik snap het, maar gezien je er nu toch mee bezig bent, en we nog weinig tijd hebben en er ook veel PR's al open staan, lijkt het mij onnodig om nog een extra taak en weer een extra PR voor deze kleine feature.

2023-06-05 20:31 UTC, Stayutazen commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +        promptExplanation.text = `Reden: ${explanation}`;
Dan moet dit ook in multiplayer gebeuren, wie houdt daar de verantwoordelijkheid voor?

2023-06-06 10:24 UTC, Koekiemonster69 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +        promptExplanation.text = `Reden: ${explanation}`;
opgelost, ik zal t zo ook ff bij de multiplayer pr aanpassen

2023-06-06 12:42 UTC, Nightshades24 requested changes

2023-06-06 12:42 UTC, Nightshades24 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +let conventionEW = "SAYC"
Moet ie dit niet uit de profielen halen?

2023-06-06 14:58 UTC, Nightshades24 approved these changes

2023-06-06 14:58 UTC, Nightshades24 commented
Ziet er zeer nice uit nu

2023-06-07 09:22 UTC, Toine1404 requested changes

2023-06-07 09:22 UTC, Toine1404 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +    }
ff comment bijzetten wat hier nou precies gebeurt. ik snap t maar tis makkelijker als je t comment

2023-06-07 09:22 UTC, Toine1404 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +    }
zelfde hier of maakr er anders ff een functie van

2023-06-07 14:22 UTC, Toine1404 submitted a review, later dismissed

2023-06-07 14:54 UTC, Nightshades24 approved these changes

2023-06-07 14:55 UTC, Toine1404 approved these changes

2023-06-07 14:56 UTC, merged