Feature 108 chat service functional
Redoublet-org/Redoublet-website pull request #62
Opened 2023-05-29 15:02 UTC by Koekiemonster69

Je kan nu chatten bij multiplayer!

2023-05-30 19:22 UTC, MatthijsdeHeus requested changes
Code ziet

2023-05-30 19:22 UTC, MatthijsdeHeus commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +
Nitpick: witregels weghalen

2023-05-30 19:22 UTC, MatthijsdeHeus commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +app.stage.addChild(chatSprite); */
Waarom is dit uit gecomment?

2023-05-30 19:22 UTC, MatthijsdeHeus commented on Redoublet-frontend/src/firebase/firebase.ts
> +  //const chatRef = ref(db, 'games/' + gameId + '/chat/');
Nitpick: comments weghalen

2023-05-30 19:22 UTC, MatthijsdeHeus commented on Redoublet-frontend/src/firebase/firebase.ts
> +  console.log(username);
Console logs mogen ook weg

2023-05-30 19:22 UTC, MatthijsdeHeus commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +
Nitpick: witregels weghalen

2023-05-30 19:22 UTC, MatthijsdeHeus commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +
Nitpick: witregel weghalen

2023-05-30 19:22 UTC, MatthijsdeHeus commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
Code werkt goed! Alleen moet de chat voor de lobbies geïmplementeerd worden ipv tijdens het spel ;)

2023-06-01 09:14 UTC, Koekiemonster69 commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +app.stage.addChild(chatSprite); */
Ik dacht eerst dat de chat in pixi moest, maar kwam er toen pas achter dat t gewoon in vue kon, heb t weggehaald

2023-06-01 09:17 UTC, Koekiemonster69 commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
Jesss, heb t nu in de lobby gegooid, was vrij makkelijk gelukkig

2023-06-01 11:37 UTC, MatthijsdeHeus submitted a review, later dismissed
Nice!

2023-06-02 14:21 UTC, Koekiemonster69 commented on Redoublet-frontend/src/views/Multiplayer/MultiplayerLobbyView.vue
> +    console.log("received new chats");
jess, maar ik zal de console log ff weghalen

2023-06-02 14:22 UTC, Koekiemonster69 commented on Redoublet-frontend/src/views/Multiplayer/MultiplayerLobbyView.vue
> +    console.log("received new chats");
dat is om te kijken of je nieuwe chats binnenkrijgt

2023-06-04 16:26 UTC, MatthijsdeHeus approved these changes

2023-06-04 16:26 UTC, MatthijsdeHeus approved these changes

2023-06-05 08:10 UTC, Toine1404 requested changes
just one tiny thing

2023-06-05 08:10 UTC, Toine1404 commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +margin: 5px, 0;
```suggestion
    margin: 5px, 0;
```

2023-06-05 08:18 UTC, Toine1404 approved these changes

2023-06-05 10:22 UTC, MatthijsdeHeus approved these changes

2023-06-05 10:34 UTC, merged