Feature 112 change profile
Redoublet-org/Redoublet-website pull request #63
Opened 2023-05-30 20:31 UTC by rubenfranquinet

Bij profiel pagina kan je nu je info aanpassen.
LET OP! pas reviewen nadat de profile page PR (129) in main zit

2023-05-31 14:26 UTC, sebas42069 requested changes
je mag nu je email en username veranderen naar dingen die al in gebruik zijn

2023-06-02 07:39 UTC, sebas42069 approved these changes
yes is goed nu!

2023-06-05 11:08 UTC, rubenfranquinet commented on Redoublet-frontend/src/firebase/firebase.ts
> +          });
Is ook meer voor ons zolang het in development zit

2023-06-05 11:12 UTC, rubenfranquinet commented on Redoublet-frontend/src/firebase/firebase.ts
> +    console.log(image)
Hoe duur het is maakt niet zo veel uit aangezien het maar 1x gebeurd en ongeveer 0.1ms duurt. Maar je hebt inderdaad wel gelijk dat het netjes is om weg te halen

2023-06-05 11:21 UTC, rubenfranquinet commented on Redoublet-frontend/src/views/Home/ProfileView.vue
> +    margin-bottom: 10px;
Ik laat dit nog even voor nu, zit namelijk ook nog geen design in, dus veel moeite hierin steken is op dit moment zonde

2023-06-05 11:23 UTC, rubenfranquinet commented on Redoublet-frontend/src/views/Home/ProfileView.vue
> +                        <option>Other</option>
Vraag voor christiaan?

2023-06-05 15:46 UTC, Toine1404 commented on Redoublet-frontend/src/views/Home/ProfileView.vue
> +                        <option>Other</option>
top

2023-06-05 15:47 UTC, Toine1404 commented on Redoublet-frontend/src/views/Home/ProfileView.vue
> +    margin-bottom: 10px;
goed punt

2023-06-05 15:49 UTC, Toine1404 commented on Redoublet-frontend/src/firebase/firebase.ts
> +    });
supah

2023-06-05 15:59 UTC, Toine1404 commented on Redoublet-frontend/src/views/Home/ProfileView.vue
> +                        <option>Prefer not to say</option>
to nog weghalen

2023-06-05 16:12 UTC, rubenfranquinet commented on Redoublet-frontend/src/views/Home/ProfileView.vue
> +    month.value = birthdate.value.getMonth() + 1;
Maanden in javascript zijn zero indexed dus van 0 tot 11 vandaar dat we bij het displayen ervan + 1 doen en bij het opslaan ervan - 1

2023-06-05 16:18 UTC, rubenfranquinet commented on Redoublet-frontend/src/views/Home/ProfileView.vue
> +        <img :src="imagePreview" alt="profile picture" width="200" height="200">
Is geen inline style, dan zou het style="width..." zijn, img heeft een propertie width en height die de width en height van de image bepalen.

2023-06-05 19:14 UTC, sebas42069 approved these changes

2023-06-05 20:26 UTC, Toine1404 requested changes

2023-06-05 20:29 UTC, rubenfranquinet commented on Redoublet-frontend/src/views/Home/ProfileView.vue
Willen we niet eerst een preview zien voordat die geupload wordt? Ik had gewoon naar wat andere sites gekeken als voorbeelden en daar heb je vaak nog een bevestiging knop. 

als je op edit klikt zie je als placeholder de gegevens die je nu hebt.

2023-06-05 20:32 UTC, Toine1404 commented on Redoublet-frontend/src/views/Home/ProfileView.vue
voor betere en intuïtievere ux  maak er anders "confirm" van

2023-06-05 20:32 UTC, Toine1404 requested changes

2023-06-05 20:32 UTC, Toine1404 commented on Redoublet-frontend/src/views/Home/ProfileView.vue
> +                class="btn btn-primary">Upload</button>
```suggestion
                class="btn btn-primary">Confirm</button>
```

2023-06-05 21:11 UTC, Toine1404 approved these changes

2023-06-06 09:03 UTC, sebas42069 approved these changes

2023-06-06 09:48 UTC, merged