Hotfix card order dummy
Redoublet-org/Redoublet-website pull request #66
Opened 2023-06-01 10:59 UTC by Toine1404

deze fix zorgt er nu voor dat de kaarten van oost en west nu ook in de juiste volgorde staan en dat dit nu ook werkt voor multiplayer. (ik was in mijn originele pr vergeten hier rekening mee te houden)

2023-06-02 11:10 UTC, sebas42069 requested changes
ehh ik heb in het draaiend bord de displaycards functie wat moeten herschrijven, en toen ik main erin mergde had ik jouw methode er wel weer in verwerkt en ook zelf een fix bedacht voor oost en west.

2023-06-02 11:10 UTC, sebas42069 commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +        for (let j = 0; j < currentGamestate.value.players[i].cards.length; j++) {
doet moet wel deal zijn ipv players.cards.
dit is om alle kaarten aan het einde van een spel te laten zien, en de normale cards arrays zijn dan leeg.
De deal onthoud wat de orginele distributie van de kaarten was aan het begin van het spel.

2023-06-07 09:28 UTC, sebas42069 submitted a review, later dismissed

2023-06-07 14:58 UTC, sebas42069 submitted a review, later dismissed

2023-06-07 15:26 UTC, Stayutazen requested changes
Ziet er goed uit! Paar comments over de structuur

2023-06-07 15:26 UTC, Stayutazen commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +        }
Kun je hier geen functie van maken aangezien het 2 keer voorkomt? Misschien kun je deze functie dan ook wat meer commenten?

2023-06-07 15:26 UTC, Stayutazen commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +let setcards2 = 0;
Is er misschien een andere manier dan 2 counters gebruiken? Begrijp niet helemaal waarom de 2 counters seperated zijn, kun je niet na het loopen van de een hem weer op 0 zetten buiten de loop? Of misschien een andere naam geven dan setcards2 (bv specifieker waar de counter voor gebruikt wordt en hoe 1 anders is dan 2)

2023-06-13 20:49 UTC, sebas42069 commented
![image](https://github.com/Redoublet-org/Redoublet-website/assets/72391324/afdb3be3-17ca-4963-b276-03fda8e98b76)

hier staan de kaarten alleen niet goed voor degene die als laatst gepassed heeft.

![image](https://github.com/Redoublet-org/Redoublet-website/assets/72391324/1d079ef4-744b-4dc3-9985-318a8efa6888)

Hier bood ik ook vanaf datzelfde tablad en veranderden de andere tabladen ook weer terug.
(maar als je van een tablad speelt waar de orderning wel goed staat dan veranderd het ene verkeerde tablad ook wel naar de goede ordening.)

oh en natuurlijk dat de biedingen nog te zien zijn tijdens de tricks phase hoort ook niet

2023-06-13 20:50 UTC, sebas42069 requested changes
![image](https://github.com/Redoublet-org/Redoublet-website/assets/72391324/afdb3be3-17ca-4963-b276-03fda8e98b76)

hier staan de kaarten alleen niet goed voor degene die als laatst gepassed heeft.

![image](https://github.com/Redoublet-org/Redoublet-website/assets/72391324/1d079ef4-744b-4dc3-9985-318a8efa6888)

Hier bood ik ook vanaf datzelfde tablad en veranderden de andere tabladen ook weer terug.
(maar als je van een tablad speelt waar de orderning wel goed staat dan veranderd het ene verkeerde tablad ook wel naar de goede ordening.)

oh en natuurlijk dat de biedingen nog te zien zijn tijdens de tricks phase hoort ook niet

2023-06-14 11:12 UTC, Stayutazen submitted a review, later dismissed
De architectuur van de code ziet er veel beter uit nu!! Ook de functie is mooi gecomment!

2023-06-19 07:35 UTC, Koekiemonster69 commented
Kaarten staan mooi in volgorde, wel kan ik door de prompt heen klikken (als in ik hoef niet eerst op OK te kliken met de prompt, weet niet hoe erg dat is.

2023-06-19 07:58 UTC, Koekiemonster69 approved these changes
Clean code! Snap alleen niet zo heel goed waarom we nou en in de back-end en in de front-end moeten sorteren? Zie ook nog comment op de main pagina over de prompt bij eindigen tricks. Ik approve wel gewoon want mini-oplevering zo, en niet heel grote foutjes, maar die prompt zou wel gefixt moeten worden eig

2023-06-19 07:58 UTC, Koekiemonster69 commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +
Dit staat ook al op line 1016 right?

2023-06-19 07:58 UTC, Koekiemonster69 commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +            numberToHand[(i + playerOffSet) % 4].addChild(cCard);
Dit staat ook op line 1003 al? of is t in methode en daarom geen code dup

2023-06-19 07:58 UTC, Koekiemonster69 commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +            numberToHand[(i + playerOffSet) % 4].addChild(cCard);
oh laat maar is in single player, zou miss mooi zijn voor de cleanup

2023-06-19 07:58 UTC, Koekiemonster69 commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +
ook voor cleanup

2023-06-19 08:35 UTC, sebas42069 commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +
wordt gedaan in de architectuur pr

2023-06-19 08:43 UTC, sebas42069 commented
@Koekiemonster69 de kaarten worden alleen gesorteerd in de backend. In de frontend zijn die 'first, second...' arrays gebruikt om ze te scheiden en dan op de goede hoogte te zetten.

het probleem met de prompt is gefixt btw

2023-06-19 10:03 UTC, sebas42069 approved these changes

2023-06-19 10:03 UTC, merged