Feature 228 visueel draaien bord
Redoublet-org/Redoublet-website pull request #71
Opened 2023-06-02 09:01 UTC by sebas42069

Bord draait nu relatief aan vanaf welk account je speelt.
Moet je testen door vier verschillende accounts te gebruiken. En als je het op 1 computer wilt doen gebruik dan op z'n minst 2 verschillende browsers en hun incognito modes om zo in totaal 4 verschillende windows te hebben.

2023-06-05 08:47 UTC, Koekiemonster69 commented
Eyo, een dingetje wat me gelijk al opvalt, dit gaat mis: Twee andere users die allebei als zuid spelen zijn allebei zuid: 
![image](https://github.com/Redoublet-org/Redoublet-website/assets/74185498/f060b054-f87e-49aa-9e49-777d436990a8)
Oke, t is heel apart, ik heb nu het eerste bod gedaan met normaal chrome, en nu is normaal chrome wel Oost geworden:
![image](https://github.com/Redoublet-org/Redoublet-website/assets/74185498/4ec7c1a0-8996-47d1-be8b-6ba6ad1b33b0)
Oke ik heb nu met zuid (incognito chrome) geboden voor noord: 
![image](https://github.com/Redoublet-org/Redoublet-website/assets/74185498/1efe8e44-c7c2-456e-93bf-d1b9ce227c72)
oh wacht dat mocht ook, want dat gaat dina fixen. Voor de rest gaat t vrij aardig vgm. Laatste dingetje is dat de punten net kloppen, maar dat is niet jouw taak denk ik: 
![image](https://github.com/Redoublet-org/Redoublet-website/assets/74185498/b3318a5f-101f-4a49-8507-2b857e1be0ce)

2023-06-05 09:14 UTC, Koekiemonster69 requested changes
Het lijkt heel veel, maar komt eigenlijk neer op console logs weghalen. Kijk wel nog ff naar de comment die ik heb gegeven op deze PR, er zit namelijk wel een flinke bug in.

2023-06-05 09:14 UTC, Koekiemonster69 commented on Redoublet-frontend/src/firebase/firebase.ts
> +  console.log("getsidefromuid");
weghalen

2023-06-05 09:14 UTC, Koekiemonster69 commented on Redoublet-frontend/src/firebase/firebase.ts
> +      console.log("nopers");
weg

2023-06-05 09:14 UTC, Koekiemonster69 commented on Redoublet-frontend/src/firebase/firebase.ts
> +      console.log("nopers");
weg

2023-06-05 09:14 UTC, Koekiemonster69 commented on Redoublet-frontend/src/firebase/firebase.ts
> +        console.log("eastid: ", id);
boeh

2023-06-05 09:14 UTC, Koekiemonster69 commented on Redoublet-frontend/src/firebase/firebase.ts
> +      console.log("nopers");
bah

2023-06-05 09:14 UTC, Koekiemonster69 commented on Redoublet-frontend/src/firebase/firebase.ts
> +      console.log("nopers");
gadsie

2023-06-05 09:14 UTC, Koekiemonster69 commented on Redoublet-frontend/src/firebase/firebase.ts
> +        console.log("southid: ", id);
nee neee nee

2023-06-05 09:14 UTC, Koekiemonster69 commented on Redoublet-frontend/src/firebase/firebase.ts
> +      console.log("side in updatecurrentuserid: ", side);
en tot slot

2023-06-05 10:47 UTC, sebas42069 commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +function checkCards() {
yes

2023-06-05 11:48 UTC, sebas42069 commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +
dit was een ding om toines volgorde van de kaarten toe te passen op deze functie, want ik had het een beetje herschreven

2023-06-05 14:58 UTC, Stayutazen submitted a review, later dismissed
Paar comments :)

2023-06-05 14:58 UTC, Stayutazen commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +//const ShuffleCards = await PIXI.Assets.load('/assets/ShuffleCards.png');
Kan eruit

2023-06-05 14:58 UTC, Stayutazen commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +    thisPlayerSide = playerSide;
kun je niet direct aanroepen thisplayerside = await getSideFromUid(lobbyKey, user.uid)?
Dit is van wat ik zie ook de enige keer dat je thisPlayerSide gebruikt

2023-06-05 14:58 UTC, Stayutazen commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +    switch (playerSide) {
Waarom gebruik je hier playerSide nadat je pas thisPlayerSide = playerSide; hebt gebruikt? Zit er een verschil tussen thisPlayerSide en playerSide?

2023-06-05 15:58 UTC, sebas42069 commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +//const ShuffleCards = await PIXI.Assets.load('/assets/ShuffleCards.png');
yes

2023-06-05 15:58 UTC, sebas42069 commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +function checkCards() {
yep

2023-06-07 09:03 UTC, Koekiemonster69 commented
![image](https://github.com/Redoublet-org/Redoublet-website/assets/74185498/7a25b9e1-8086-436f-9d12-92ce5e9f5357)
ik krijg zoiezo dit, waarbij die voor 1 speler niet goed opstart. Ik ga ff opnieuw opstarte.
![image](https://github.com/Redoublet-org/Redoublet-website/assets/74185498/67733f97-50fe-4a5c-8520-4bfc76751517)
Deze error krijg ik als ik refresh in de host game.
Ik krijg ook zo'n zelfde error als ik probeer te chatten met twee andere schermen
![image](https://github.com/Redoublet-org/Redoublet-website/assets/74185498/0736e9da-c004-4556-bcb6-3d30b8f1be4c)
in game klopt t wel aardig
![image](https://github.com/Redoublet-org/Redoublet-website/assets/74185498/0e6fab32-efb3-4863-bfdf-2f6109d483d1)

2023-06-13 08:51 UTC, Koekiemonster69 commented
ik heb nog steeds dit
![image](https://github.com/Redoublet-org/Redoublet-website/assets/74185498/c104b2d3-1980-4fa0-a99f-73835fb07def)
twee keer south met een ander account

2023-06-13 09:22 UTC, Koekiemonster69 requested changes
zie comment

2023-06-14 08:49 UTC, Koekiemonster69 submitted a review, later dismissed
Ziet er goed uit! alleen nog ff main erin mergen zodat conventies kloppen

2023-06-14 09:21 UTC, Koekiemonster69 requested changes
Bied advies is gesloopt, verder laat ie ook nog niet NS en OW conventie goed zien, maar weet van dat laatste niet 100% zeker of t aan jou ligt

2023-06-15 13:34 UTC, Stayutazen requested changes
Bij mij werkt biedadvies ook niet. Verder gewoon even de harcoded SAYC conventies veranderen in de conventie variabele in updatePixi. Als dit weer werkt zou ik zeggen dat het wel goed is!

2023-06-16 11:08 UTC, Koekiemonster69 approved these changes

2023-06-16 17:26 UTC, Stayutazen approved these changes
Lijkt te werken!

2023-06-16 17:34 UTC, merged