Feature 254 multiplayer implementatie bied uitleg
Redoublet-org/Redoublet-website pull request #73
Opened 2023-06-04 10:40 UTC by Koekiemonster69

Deze PR kan al gedaan worden, het is alleen van belang dat elke speler in de lobby een conventie heeft. Dat kan handmatig via de firebase, of als de conventie toevoegen PR gedaan is. 

Zie JIRA voor omschrijving taakje

2023-06-06 13:17 UTC, rubenfranquinet requested changes

2023-06-07 09:11 UTC, rubenfranquinet reviewed
Ik krijg de volgende error bij het klikken op iemands anders zijn bod:
![image](https://github.com/Redoublet-org/Redoublet-website/assets/64008619/d6702be0-15b4-45e2-9567-3022be4032a9)

2023-06-08 11:57 UTC, Nightshades24 requested changes
Ik krijg deze foutmelding als ik op een bod klik 
![image](https://github.com/Redoublet-org/Redoublet-website/assets/71764800/06bde83f-e887-457c-9d91-7fb829dc0110)

2023-06-08 13:40 UTC, Nightshades24 requested changes
Code ziet er goed uit. Klein dingetje alleen: je moet even alle API calls afgaan en zorgen dat deze await worden, net zoals ik bij de pixicomponent had gedaan, want dat gebeurt nog niet. Hoort niet echt bij jouw PR, maar moet wel zsm gebeuren en het is een klein taakje.

2023-06-08 15:01 UTC, Nightshades24 requested changes

2023-06-08 15:08 UTC, rubenfranquinet approved these changes

2023-06-08 15:14 UTC, Nightshades24 approved these changes

2023-06-08 15:14 UTC, merged