Feature 305 handle leaven host
Redoublet-org/Redoublet-website pull request #77
Opened 2023-06-05 14:25 UTC by rubenfranquinet

LET OP: pas reviewen als 245 lobbies conventies in main zit en hierin gemerged is.

Als host leaved en er zijn andere spelers dan wordt een ander de host
Als host leaved en er is niemand dan wordt de game verwijderd

2023-06-08 14:30 UTC, Nightshades24 requested changes

2023-06-08 14:30 UTC, Nightshades24 commented on Redoublet-frontend/src/firebase/firebase.ts
> +//update email for userid
```suggestion
// Update email for userid
```

2023-06-08 14:30 UTC, Nightshades24 commented on Redoublet-frontend/src/firebase/firebase.ts
> +//update gender for userid
```suggestion
// Update gender for userid
```

2023-06-08 14:30 UTC, Nightshades24 commented on Redoublet-frontend/src/firebase/firebase.ts
> +//update profile picture for userid
```suggestion
// Update profile picture for userid
```

2023-06-08 14:30 UTC, Nightshades24 commented on Redoublet-frontend/src/views/Multiplayer/MultiplayerLobbyView.vue
> +
```suggestion
```

2023-06-13 10:58 UTC, Nightshades24 requested changes

2023-06-13 10:58 UTC, Nightshades24 commented on Redoublet-frontend/src/views/Home/ProfileView.vue
> -© Copyright Utrecht University (Department of Information and Computing Sciences)
Zet deze even terug

2023-06-13 10:58 UTC, Nightshades24 commented on Redoublet-frontend/src/views/Home/ProfileView.vue
> +import { getUserImage, getUsername, getBirthdate, getGender, getNationality, getEmail, getConvention, changeConvention, updateUsername, updateImage, updateBirthdate, updateUserEmail, updateGender, up
```suggestion
import { getUserImage, getUsername, getBirthdate, getGender, getNationality, getEmail, getConvention, changeConvention, updateUsername, updateImage, updateBirthdate, updateUserEmail, updateGender, updateNationality } from '../../firebase/firebase';
```

2023-06-13 10:58 UTC, Nightshades24 commented on Redoublet-frontend/src/views/Home/ProfileView.vue
Je hebt de change email gesloopt. Fix dit even

2023-06-13 11:07 UTC, Nightshades24 submitted a review, later dismissed
Lekker pik!!!!!!!!!!!!!!!!!!!!!!

![Alt Text](https://media.tenor.com/XUAONVsG6qIAAAAC/leonardo-dicaprio-clapping.gif)

2023-06-13 13:27 UTC, Nightshades24 requested changes
INSECT GESPOT: als iemand nog geen kant heeft gekozen, maar alle spelers die dit al wel hadden het spel hebben verlaten, wordt de lobby verwijderd, maar blijft de speler die nog geen kant had gekozen wel in de lobby zitten, maar deze werkt niet meer

2023-06-13 13:30 UTC, Koekiemonster69 reviewed
eerst is dat t nice zou zijn als de conventie wordt gerefresht als jij een teammate joined en die tm8 vervolgens leavet. Dara hadden we t gisteren met christiaan over gehad en dat was wat ie wilde. Maar je mag ook zeggen niet mijn scope f u

Als Persoon A lobby 1 aanmaakt, persoon B die joint, p. A die leavet en lobby 2 aanmaakt, en persson B lobby 1 leavet, wordt ook A uit lobby 2 geleavet

2023-06-13 15:19 UTC, Nightshades24 requested changes
Er zit nu alleen nog qua bug in dat wanneer je teammate met andere conventie leaved, de conventie niet wordt aangepast naar jouw conventie. Dit moet je nog even fixen

2023-06-13 20:03 UTC, Nightshades24 commented on Redoublet-frontend/src/views/Multiplayer/MultiplayerLobbyView.vue
> +        // resetGameData();
```suggestion
```

2023-06-13 20:07 UTC, Nightshades24 requested changes

2023-06-13 20:07 UTC, Nightshades24 commented on Redoublet-frontend/src/views/Multiplayer/MultiplayerLobbyView.vue
> +
```suggestion
```

2023-06-13 20:07 UTC, Nightshades24 commented on Redoublet-frontend/src/views/Multiplayer/MultiplayerLobbyView.vue
> +        console.log("Resetting data")
```suggestion
        // Delete game
```

2023-06-13 20:07 UTC, Nightshades24 commented on Redoublet-frontend/src/views/Multiplayer/MultiplayerLobbyView.vue
> +
```suggestion
```

2023-06-13 20:09 UTC, Nightshades24 approved these changes

2023-06-14 08:36 UTC, Koekiemonster69 approved these changes
mooi insect platgeslagen

2023-06-14 08:39 UTC, merged