feature 246 prive lobbies
Redoublet-org/Redoublet-website pull request #82
Opened 2023-06-12 20:26 UTC by Nightshades24

Je kan nu een wachtwoord op je lobby zetten wanneer je een lobby aanmaakt. (LET OP DAT JE DIT TEST MET ZELF EEN LOBBY AANMAKEN, LOBBY'S AANGEMAAKT IN ANDERE BRANCHES HEBBEN GEEN PASSWORD VARIABELE!)
Wanneer je dit leeg laat komt er geen wachtwoord op de lobby te staan en is hij open.
In de lobby selectie is een extra kolom toegevoegd die aangeeft of een lobby open of private is. Ook zegt de knop "Enter Password" als de lobby prive is ipv "Join Game".
Let ook vooral even op het menu om de lobby aan te maken, ik vraag me namelijk af of dat op deze manier duidelijk genoeg is. Het kan namelijk eventueel een checkbox worden die vraagt of je lobby private moet zijn, en dat dan de textbox verschijnt wanneer je deze aanvinkt.

2023-06-12 21:05 UTC, tvdplas requested changes

2023-06-12 21:05 UTC, tvdplas commented on Redoublet-frontend/src/views/Multiplayer/MultiplayerTableJoinView.vue
> +  </div>
Vertalen naar Nederlands aangezien het password setten ook in NL staat

2023-06-12 21:05 UTC, tvdplas commented on Redoublet-frontend/src/views/Multiplayer/MultiplayerTableJoinView.vue
> +    router.push("/multiplayer-lobby/" + gameKeyToJoin.value);
Betekent dit nou dat je lokaal de check doet of het wachtwoord doet? If so, is dit een security risico wat we willen accepteren of is het miss handiger om server side af te handelen zodat de client nooit het wachtwoord van de te joinen server ziet?

2023-06-12 21:06 UTC, tvdplas commented on Redoublet-frontend/src/components/CreateGameGrid.vue
> +    <button class="my-4" type="submit">
Iets van een checkbox zou dit probleem inderdaad ook oplossen, misschien is dat een beter idee. Want ik weet niet of onze lieve oudjes het anders goed begrijpen

2023-06-13 08:10 UTC, Nightshades24 commented on Redoublet-frontend/package-lock.json
Vgm niet, ik had gwn npm install opnieuw gerund dus zal wss daardoor komen, zal ff kijken of ie nog werkt als ik deze changes weghaal

2023-06-13 08:11 UTC, Nightshades24 commented on Redoublet-frontend/src/components/CreateGameGrid.vue
> +    <button class="my-4" type="submit">
Denk inderdaad dat dit duidelijker is

2023-06-13 08:12 UTC, Nightshades24 commented on Redoublet-frontend/src/views/Multiplayer/MultiplayerTableJoinView.vue
> +    router.push("/multiplayer-lobby/" + gameKeyToJoin.value);
Heb jij enig idee hoe we dit server side zouden kunnen doen dan? Lijkt me namelijk best gezeik dus allicht dat we voor nu gewoon dit risico willen accepteren

2023-06-13 08:54 UTC, tvdplas commented on Redoublet-frontend/src/views/Multiplayer/MultiplayerTableJoinView.vue
> +    router.push("/multiplayer-lobby/" + gameKeyToJoin.value);
Understandable, have a nice day

2023-06-13 10:52 UTC, tvdplas approved these changes
Ik vind gelemaal mooi

2023-06-13 11:47 UTC, rubenfranquinet approved these changes
Leuk joh, wat is al deze CSS troep joh

2023-06-13 11:47 UTC, merged