Feature 316 lobby filter en delete
Redoublet-org/Redoublet-website pull request #84
Opened 2023-06-15 14:20 UTC by rubenfranquinet

De lijst met lobbies is nu een gefilterde lijst, hier zie je alleen de lobbies die nog gestart moeten worden.

Een spel heeft nu ook een knop om er weg te gaan, als iedereen weg is dan verwijderd het spel uit de database.

2023-06-17 12:55 UTC, sebas42069 requested changes
![image](https://github.com/Redoublet-org/Redoublet-website/assets/72391324/75ee3680-b71f-4464-9ddc-454a9c5ef06d)
![image](https://github.com/Redoublet-org/Redoublet-website/assets/72391324/7d4d4b1b-324c-4eb9-8fe8-aacb658bbd05)
![image](https://github.com/Redoublet-org/Redoublet-website/assets/72391324/ac35eae0-a1e2-46e7-9b90-b60c66c0c730)

wanneer je op leave game drukt in een lobby waar je nog niet een plaats hebt genomen worden de conventies van oost en west op open gezet. Ook als er op beide plekken wel al spelers hun plaats hebben genomen.

2023-06-20 13:42 UTC, tvdplas requested changes

2023-06-20 13:42 UTC, tvdplas commented on Redoublet-frontend/src/views/Multiplayer/MultiplayerGameView.vue
> +            router.push({ path: '/multiplayer-table' });
Kan je voor deze code een functie maken die als argument de richting meeneemt? Dan hoeft dit niet gedupliceerd te worden voor de verschillende richtingen

2023-06-20 13:42 UTC, tvdplas commented on Redoublet-frontend/src/views/Multiplayer/MultiplayerTableJoinView.vue
> +  /* Make the prompt appear on top of everything */
Ff commentje terugzetten op juiste regel
```suggestion
  z-index: 9999; /* Make the prompt appear on top of everything */
```

2023-06-20 13:42 UTC, tvdplas commented
Daarnaast mag dit niet gemerged worden tot auth in main weer werkt

2023-06-21 10:21 UTC, sebas42069 approved these changes
toppie

2023-06-22 07:28 UTC, merged