Feature 317 chat styling
Redoublet-org/Redoublet-website pull request #86
Opened 2023-06-16 14:30 UTC by Koekiemonster69

Alsjeblieft niet uitlachen :(
Nee geintje mag best, is voor het eerst dat ik CSS doe

2023-06-16 18:19 UTC, Stayutazen requested changes
Ziet er hartstikke leuk uit joh!! De code is alleen css waar ik niet veel op heb aan te merken, dus ik zal het even bij de visuals laten:
- Het zou er mooi uitzien als de tekst in de input box ook wit is!
![afbeelding](https://github.com/Redoublet-org/Redoublet-website/assets/78958488/9a207650-5f92-49ba-a7d4-c003592f8306)

- General styling van de box, er zitten white spaces tussen de 'chatbox' naam box en de echte chatbox, en ook tussen de chatbox en de input box. Het zou nice zijn als dit allemaal op elkaar zit. Ook zijn ze niet even breed als de chatbox zelf.
![afbeelding](https://github.com/Redoublet-org/Redoublet-website/assets/78958488/a996cb75-2e10-4724-b8b9-f0c8b7501d59)
![afbeelding](https://github.com/Redoublet-org/Redoublet-website/assets/78958488/5e845105-bc5a-4213-97ea-e37d00a0d71c)

- Voor de input box, ik weet niet of het er ook zo bij jou uitziet maar de send message button overlapped over de rand van het input veld? Dit is ook niet gewenst maar ik weet niet of dit ligt aan de css of dat verschillende schermen een ander effect creëren
![afbeelding](https://github.com/Redoublet-org/Redoublet-website/assets/78958488/df48338e-3c19-495a-aabe-5786e557b2a8)

- Er moet ook padding/margin zitten tussen de profielfoto en de rand van de chatbox (links). Ook bij de het inputveld moet er boven & onder padding komen zodat de donkere box groter is dan de lichtere inputbox :)
![afbeelding](https://github.com/Redoublet-org/Redoublet-website/assets/78958488/fcd256c8-a7a6-4474-80da-e164c5fa1b9c)
![afbeelding](https://github.com/Redoublet-org/Redoublet-website/assets/78958488/600ab9d7-1387-4eb8-9154-ee3436794bc5)

- Complimentje: De chatbox zelf ziet er echt mooi uit!!
![afbeelding](https://github.com/Redoublet-org/Redoublet-website/assets/78958488/3c60f066-a098-4507-ad66-3b2d0c9bee3b)

General note: willen we ook dat iemands gebruikersnaam bij het bericht staat ipv alleen een profielfoto? Kan me bedenken dat het niet heel gewenst is voor oudere mensen om er geen gebruikersnaam bij te zien

2023-06-19 11:43 UTC, Stayutazen requested changes
Ziet er een stuk beter uit!! Nog wat kleine puntjes

Over de input box:
- Ik zou evenveel padding toevoegen voor de tekst als na het verstuur knopje
![afbeelding](https://github.com/Redoublet-org/Redoublet-website/assets/78958488/8a38d8ac-35f0-4260-a7a4-a6f765070df1)
- Is het mogelijk die gele/beige rand weg te halen? Deze zat namelijk niet bij het voorbeeld van de artists
![afbeelding](https://github.com/Redoublet-org/Redoublet-website/assets/78958488/9a224060-2855-4e04-b236-7f833bd5f281)
- Misschien is de inputbox breder maken wat chiller? En ook wat hoger? Het is nu namelijk heel compressed
![afbeelding](https://github.com/Redoublet-org/Redoublet-website/assets/78958488/8c54ae1c-f904-40d0-b727-99c6031f4c6b)
![afbeelding](https://github.com/Redoublet-org/Redoublet-website/assets/78958488/088bdc9f-f97e-4747-8711-a383e1e309cd)

Over de chatbox:

- De placement van de gebruikersnamen is echt nice! Maar ik zou er nog wat extra padding rechts toevoegen aangezien momenteel de tekst bijna wordt afgesneden/niet goed te lezen is omdat hij op de rand staat en we een lichte achtergrond hebben voor de website.
![afbeelding](https://github.com/Redoublet-org/Redoublet-website/assets/78958488/b9cdf854-137e-48fa-aea3-5d8cd2fa2c85)
- Meer een vraagje maar hebben we de scrollbar liever binnen of buiten de chatbox? Binnen lijkt me zelf nicer maar ik weet niet wat jij vindt/ of dat uberhaupt zou lukken?
![afbeelding](https://github.com/Redoublet-org/Redoublet-website/assets/78958488/1e6c6d09-4c1f-4698-9416-81eabaa2df3c)
- Kleine nitpick maar het is wel iets wat me gelijk opviel en denk ik makkelijk te fixen als je toch bezig bent
![afbeelding](https://github.com/Redoublet-org/Redoublet-website/assets/78958488/2864ab47-5991-466c-abb4-2d0f9e383000)

2023-06-21 11:23 UTC, Stayutazen submitted a review, later dismissed
Toppie!!!!

2023-06-21 14:42 UTC, Stayutazen approved these changes
Top!! Verwerking van artists ziet er nicer uit!

2023-06-22 09:35 UTC, rubenfranquinet approved these changes
Ziet er gewoon hartstikke prima uit

2023-06-22 09:35 UTC, merged