Feature 288 optimale contract
Redoublet-org/Redoublet-website pull request #92
Opened 2023-06-21 15:50 UTC by Toine1404

added optimal contracts  for the dealer pair by updating the analyse contract functionality in the front end and facilitating that with some extra classes and methods in the back end. Try to test this multiple times and see if it works. there is still a button in there for easy testing!

2023-06-21 17:56 UTC, sebas42069 requested changes
werkt prima in singleplayer. heb een paar suggesties gedaan zodat het in multiplayer ook werkt.

Ook is er heel veel lege ruimte boven de dds analyse, maar voor mij gebeurd dat alleen bij multiplayer. Ik had zelf even gekeken en kon niet echt vinden waardoor dat kwam, maar misschien dat jij het wel al weet.

![image](https://github.com/Redoublet-org/Redoublet-website/assets/72391324/4fd3d5b6-6f18-4389-a810-8926b271cb97)

2023-06-21 17:56 UTC, sebas42069 commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +    body: JSON.stringify(currentGamestate.value.dealer)
```suggestion
    body: JSON.stringify(currentGamestate.dealer)
```

in multiplayer is de gamestate geen ref, dus heeft het geen value property.

2023-06-21 17:56 UTC, sebas42069 commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +        NS: currentGamestate.value.vulnerableNS,
```suggestion
        NS: currentGamestate.vulnerableNS,
```

2023-06-21 17:56 UTC, sebas42069 commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +        EW: currentGamestate.value.vulnerableEW,
```suggestion
        EW: currentGamestate.vulnerableEW,
```

2023-06-21 17:56 UTC, sebas42069 commented on Redoublet-backend/Redoublet-backend/Services/DDSService.cs
> +
deze drie drie functies comments geven

2023-06-22 09:58 UTC, sebas42069 submitted a review, later dismissed
lijkt prima nu

2023-06-22 10:32 UTC, Nightshades24 requested changes

2023-06-22 10:32 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Services/DDSService.cs
> +            return json;
```suggestion
            switch (dealer)
            {
                case "South":
                    return JsonConvert.SerializeObject(1);
                case "North":
                    return JsonConvert.SerializeObject(0);
                case "East":
                    return JsonConvert.SerializeObject(2);
                case "West":
                    return return JsonConvert.SerializeObject(3);
                default:
                    return "";
            }
```

2023-06-22 10:32 UTC, Nightshades24 commented on Redoublet-backend/Redoublet-backend/Services/DDSService.cs
> +            return json;
```suggestion
            if (input.EW && input.NS)
            {
                return JsonConvert.SerializeObject(1);
            }
            else if (!input.EW && !input.NS)
            {
                return JsonConvert.SerializeObject(0);
            }
            else if (!input.EW && input.NS)
            {
                return JsonConvert.SerializeObject(2);
            }
            else if (input.EW && !input.NS)
            {
                return JsonConvert.SerializeObject(3);
            }
            else
            {
                return "";
            }
```

2023-06-22 10:32 UTC, Nightshades24 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +
```suggestion
```

2023-06-22 10:32 UTC, Nightshades24 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +    <button @click="analyse">analyseer</button>
```suggestion
    <button @click="analyse">Analyseer</button>
```

2023-06-22 10:32 UTC, Nightshades24 commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +}
Doe al deze functies even een tab en dan kan je de witregel boven en onder weghalen.

2023-06-22 10:32 UTC, Nightshades24 commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +
```suggestion
```

2023-06-22 10:32 UTC, Nightshades24 commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +
```suggestion
```

2023-06-22 10:32 UTC, Nightshades24 commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +    <button @click="analyse">analyseer</button>
```suggestion
    <button @click="analyse">Analyseer</button>
```

2023-06-22 11:29 UTC, Toine1404 commented on Redoublet-frontend/src/components/Pixi/PixiMultiplayerComponent.vue
> +}
note to self: haal analyseer knop weg

2023-06-22 14:36 UTC, Nightshades24 requested changes
Kreeg de 2e keer dat ik het testte deze foutmelding
![image](https://github.com/Redoublet-org/Redoublet-website/assets/71764800/0f8fc6ff-1127-45ae-b5de-699f17d56176)

2023-06-22 14:36 UTC, Nightshades24 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +
```suggestion
```

2023-06-22 16:54 UTC, Nightshades24 requested changes

2023-06-22 16:54 UTC, Nightshades24 commented on Redoublet-frontend/src/components/Pixi/PixiComponent.vue
> +
```suggestion
```

2023-06-22 20:41 UTC, sebas42069 approved these changes

2023-06-22 20:47 UTC, Nightshades24 approved these changes

2023-06-22 20:59 UTC, merged