311 architectuur pixi
Redoublet-org/Redoublet-website pull request #95
Opened 2023-06-24 23:49 UTC by sebas42069

Archtectuur van pixi is veranderd. Veel dingen zijn ge-extract en gestopt in de PixiHelpers folder.
Er zijn nog een aantal functies die in beide pixi components zitten, maar daar kon ik niet echt goed extracten.

ook in deze pr:
- vulnerable zichtbaar
- (re)doubleren contract

2023-06-26 12:27 UTC, rubenfranquinet requested changes
Je kan nu doubleren, redoubleren en passen voor andere spelers, Bizar!

2023-06-26 12:27 UTC, rubenfranquinet commented on Redoublet-frontend/src/PixiHelpers/DisplayFunctions/displayContract.ts
Hele mooie file!!!

Geen fouten in gevonden!

2023-06-26 13:00 UTC, rubenfranquinet approved these changes

2023-06-26 20:13 UTC, tvdplas requested changes
DEZE REVIEW IS ALLEEN OVER DE CODE; FUNCTIONALITEIT IS **NIET** GETEST.

Nog een aantal opmerkingen over de code, let op dat de magic number comments betrekking hebben tot heel veel van de bestanden, ik heb er een paar aangevinkt maar je zou zelf nog ff moeten kijken waar het allemaal staat.

Over het algemeen tho, respect voor deze refactoring :')

2023-06-26 20:13 UTC, tvdplas commented on Redoublet-frontend/src/PixiHelpers/Classes/BidSprite.ts
> +        this.texture = PIXI.Texture.from("/assets/Placeholders/NewBiddingBox/" + suit + value + ".png");
Is het nodig om texture hier twee keer te setten?

2023-06-26 20:13 UTC, tvdplas commented on Redoublet-frontend/src/PixiHelpers/Classes/PlayerBidSprite.ts
> +        }
Switch over `suit`, maar opties zijn pass, double, redouble? Lijkt me eerder een actie dan toch? Misschien ff naam aanpassen

2023-06-26 20:13 UTC, tvdplas commented on Redoublet-frontend/src/PixiHelpers/DisplayFunctions/currentPlayerHighlight.ts
Heel veel magic numbers (text kleur, kaart width/height). Misschien handig om als variabelen te definieren bovenaan het bestand / helemaal extracten naar een aparte config file

2023-06-26 20:13 UTC, tvdplas commented on Redoublet-frontend/src/PixiHelpers/DisplayFunctions/displayAllCardsOpen.ts
> +                    }
Zie ook comment hierboven, width and height worden hier (naar mijn idee) als magic numbers gebruikt. Ik zou ergens een .ts file met constants maken die dit definieert, zodat je die gewoon kan importeren

2023-06-26 20:13 UTC, tvdplas commented on Redoublet-frontend/src/PixiHelpers/DisplayFunctions/displayCards.ts
> +            }
magic width

2023-06-26 20:13 UTC, tvdplas commented on Redoublet-frontend/src/PixiHelpers/DisplayFunctions/displayCards.ts
> +                            break;
Magic width

2023-06-26 20:13 UTC, tvdplas commented on Redoublet-frontend/src/PixiHelpers/DisplayFunctions/displayCards.ts
> +                }
Die `(i + playerOffset) % 4` array access komt ook heel vaak voor. Is het misschien mogelijk om hier een functietje voor te maken? Dan kan je het ook een iets duidelijkere naam geven

2023-06-26 20:13 UTC, tvdplas commented on Redoublet-frontend/src/PixiHelpers/references.ts
> +}
Is er een rede dat suits wel met hoofdletters zijn en card values niet?

2023-06-26 20:13 UTC, tvdplas commented on Redoublet-frontend/src/PixiHelpers/startGame.ts
> +        console.log("json", JSONresult);
Console logjes

2023-06-27 10:26 UTC, sebas42069 commented on Redoublet-frontend/src/PixiHelpers/DisplayFunctions/displayCards.ts
> +                }
yes goeie

2023-06-27 10:26 UTC, sebas42069 commented on Redoublet-frontend/src/PixiHelpers/Firebase/getSideConvention.ts
> +}
yep

2023-06-27 10:26 UTC, sebas42069 commented on Redoublet-frontend/src/PixiHelpers/references.ts
> +}
de valueNames wordt gebruikt om de card sprites te vinden, en die namen zijn lowercase

2023-06-27 10:26 UTC, sebas42069 commented on Redoublet-frontend/src/PixiHelpers/startGame.ts
> +        console.log("json", JSONresult);
oja

2023-06-27 11:09 UTC, tvdplas submitted a review, later dismissed
nice

2023-06-27 12:58 UTC, tvdplas approved these changes
cool

2023-06-27 12:58 UTC, merged